let DATA = {
    Amh_Araeng: [
        {level: '70', hunt: false, name: '톨바', location: '아므 아랭', coordinate: '( 31.6, 22.5 )', drop: '&nbsp'},
        {level: '70', hunt: true, name: '모래두더지', location: '아므 아랭', coordinate: '( 31.6, 22.5 )', drop: '&nbsp'},
        {level: '70', hunt: false, name: '응고지', location: '아므 아랭', coordinate: '( 32.9, 25.3 )', drop: '&nbsp'},
        {level: '70', hunt: true, name: '고대 도마뱀', location: '아므 아랭', coordinate: '( 32.9, 25.3 )', drop: '&nbsp'},
        {level: '70', hunt: true, name: '가위턱', location: '아므 아랭', coordinate: '( 30.9, 26.7 )', drop: '&nbsp'},
        {level: '70', hunt: true, name: '굴람', location: '아므 아랭', coordinate: '( 27.7, 30.0 )', drop: '&nbsp'},
        {level: '70', hunt: false, name: '모래먹이', location: '아므 아랭', coordinate: '( 27.5, 25.7 )', drop: '&nbsp'},
        {level: '76', hunt: false, name: '수확거미', location: '아므 아랭', coordinate: '( 19.2, 24.8 )', drop: '&nbsp'},
        {level: '76', hunt: true, name: '무기마', location: '아므 아랭', coordinate: '( 21.7, 23.8 )', drop: '&nbsp'},
        {level: '76', hunt: true, name: '가시두더지', location: '아므 아랭', coordinate: '( 16.8, 20.9 )', drop: '&nbsp'},
        {level: '76', hunt: false, name: '마른가시 기가텐더', location: '아므 아랭', coordinate: '( 16.8, 20.9 )', drop: '&nbsp'},
        {level: '76', hunt: true, name: '흙보듬이', location: '아므 아랭', coordinate: '( 14.6, 18.8 )', drop: '&nbsp'},
        {level: '76', hunt: true, name: '포루스라코스', location: '아므 아랭', coordinate: '( 17.3, 15.9 )', drop: '&nbsp'},
        {level: '76', hunt: true, name: '노움', location: '아므 아랭', coordinate: '( 10.0, 22.8 )', drop: '&nbsp'},
        {level: '76', hunt: true, name: '거대박쥐', location: '아므 아랭', coordinate: '( 10.0, 22.8 )', drop: '&nbsp'},
        {level: '76', hunt: true, name: '호박 이구아나', location: '아므 아랭', coordinate: '( 12.4, 13.6 )', drop: '&nbsp'},
        {level: '76', hunt: true, name: '수컷 오뷤', location: '아므 아랭', coordinate: '( 16.1, 13.2 )', drop: '<a href=\'https://ff14.tar.to/item/list/?redirect=true&quick-search-option=item&keyword=%EC%98%A4%EB%B7%A4%EC%9D%98+%ED%84%B8\' id=\'drop\' target=\'_blank\'>오뷤의 털</a><br><a href=\'https://ff14.tar.to/item/list/?redirect=true&quick-search-option=item&keyword=%EC%98%A4%EB%B7%A4+%EA%B3%A0%EA%B8%B0\' id=\'drop\' target=\'_blank\'>오뷤 고기</a>'},
        {level: '76', hunt: true, name: '암컷 오뷤', location: '아므 아랭', coordinate: '( 16.1, 13.2 )', drop: '<a href=\'https://ff14.tar.to/item/list/?redirect=true&quick-search-option=item&keyword=%EC%98%A4%EB%B7%A4%EC%9D%98+%ED%84%B8\' id=\'drop\' target=\'_blank\'>오뷤의 털</a><br><a href=\'https://ff14.tar.to/item/list/?redirect=true&quick-search-option=item&keyword=%EC%98%A4%EB%B7%A4+%EA%B3%A0%EA%B8%B0\' id=\'drop\' target=\'_blank\'>오뷤 고기</a>'},
        {level: '76', hunt: true, name: '코요테', location: '아므 아랭', coordinate: '( 21.5, 9.9 )', drop: '&nbsp'},
        {level: '77', hunt: true, name: '모래도롱뇽', location: '아므 아랭', coordinate: '( 23.7, 31.6 )', drop: '&nbsp'},
        {level: '77', hunt: true, name: '화염 조누르', location: '아므 아랭', coordinate: '( 27.0, 34.7 )', drop: '<a href=\'https://ff14.tar.to/item/list/?keyword=%EC%A1%B0%EB%88%84%EB%A5%B4+%EC%83%9D%EA%B0%80%EC%A3%BD\' id=\'drop\' target=\'_blank\'>조누르 생가죽</a>'},
        {level: '77', hunt: true, name: '긴꼬리 아르마딜로', location: '아므 아랭', coordinate: '( 17.4, 31.8 )', drop: '&nbsp'},
        {level: '77', hunt: true, name: '주인 없는 탈로스', location: '아므 아랭', coordinate: '( 11.5, 31.5 )', drop: '&nbsp'},
        {level: '80', hunt: 'B', name: '학살 곡예마', location: '아므 아랭', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'B', name: '우물 지렁이', location: '아므 아랭', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'T', name: '면죄된 험담', location: '아므 아랭', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'A', name: '말리크텐더', location: '아므 아랭', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'A', name: '슈가르', location: '아므 아랭', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'S', name: '타르키아', location: '아므 아랭', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'SS', name: '면죄된 폭동', location: '아므 아랭', coordinate: '( 27.5, 35.3 )', drop: '&nbsp'}
    ],
    Lakeland: [
        {level: '71', hunt: true, name: '깡총풀', location: '레이크랜드', coordinate: '( 35.6, 27.5 )', drop: '<a href=\'https://ff14.tar.to/item/list/?keyword=%EA%B9%A1%EC%B4%9D%ED%92%80+%EC%9E%8E\' id=\'drop\' target=\'_blank\'>깡총풀 잎</a>'},
        {level: '71', hunt: true, name: '오소리', location: '레이크랜드', coordinate: '( 30.0, 36.9 )', drop: '&nbsp'},
        {level: '71', hunt: true, name: '거대 이구아나', location: '레이크랜드', coordinate: '( 26.3, 32.3 )', drop: '&nbsp'},
        {level: '71', hunt: true, name: '호수 독사', location: '레이크랜드', coordinate: '( 20.8, 24.7 )', drop: '&nbsp'},
        {level: '71', hunt: true, name: '습지 바르그', location: '레이크랜드', coordinate: '( 23.1, 21.4 )', drop: '&nbsp'},
        {level: '71', hunt: true, name: '호수 아네모네', location: '레이크랜드', coordinate: '( 13.8, 23.0 )', drop: '&nbsp'},
        {level: '71', hunt: true, name: '조누르', location: '레이크랜드', coordinate: '( 11.0, 18.4 )', drop: '&nbsp'},
        {level: '71', hunt: true, name: '놀', location: '레이크랜드', coordinate: '( 13.4, 16.4 )', drop: '&nbsp'},
        {level: '71', hunt: true, name: '비단나방', location: '레이크랜드', coordinate: '( 17.1, 15.9 )', drop: '<a href=\'https://ff14.tar.to/item/list/?keyword=%EB%B9%84%EB%8B%A8%EB%82%98%EB%B0%A9+%EB%B9%84%EB%8A%98%EA%B0%80%EB%A3%A8\' id=\'drop\' target=\'_blank\'>비단나방 비늘가루</a>'},
        {level: '71', hunt: true, name: '스밀로돈', location: '레이크랜드', coordinate: '( 11.5, 11.2 )', drop: '<a href=\'https://ff14.tar.to/item/list/?keyword=%EC%8A%A4%EB%B0%80%EB%A1%9C%EB%8F%88+%EC%83%9D%EA%B0%80%EC%A3%BD\' id=\'drop\' target=\'_blank\'>스밀로돈 생가죽</a>'},
        {level: '71', hunt: true, name: '천년 카마', location: '레이크랜드', coordinate: '( 16.8, 9.8 )', drop: '&nbsp'},
        {level: '71', hunt: true, name: '프로테로수쿠스', location: '레이크랜드', coordinate: '( 28.1, 18.6 )', drop: '&nbsp'},
        {level: '71', hunt: true, name: '엘프 기사', location: '레이크랜드', coordinate: '( 24.9, 17.1 )', drop: '&nbsp'},
        {level: '71', hunt: false, name: '나그네불', location: '레이크랜드', coordinate: '( 24.9, 17.1 )', drop: '&nbsp'},
        {level: '71', hunt: true, name: '코엘로사우루스', location: '레이크랜드', coordinate: '( 25.1, 11.8 )', drop: '&nbsp'},
        {level: '71', hunt: true, name: '백색 그렘린', location: '레이크랜드', coordinate: '( 32.8, 8.4 )', drop: '&nbsp'},
        {level: '71', hunt: false, name: '회색 드라코', location: '레이크랜드', coordinate: '( 35.2, 14.0 )', drop: '&nbsp'},
        {level: '71', hunt: true, name: '야테베오', location: '레이크랜드', coordinate: '( 32.8, 18.5 )', drop: '&nbsp'},
        {level: '71', hunt: true, name: '보라 트리피드', location: '레이크랜드', coordinate: '( 29.1, 22.0 )', drop: '&nbsp'},
        {level: '80', hunt: 'B', name: '이츠파팔로틀', location: '레이크랜드', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'B', name: '털보 오소리', location: '레이크랜드', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'T', name: '면죄된 험담', location: '레이크랜드', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'A', name: '너클라비', location: '레이크랜드', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'A', name: '나리폰', location: '레이크랜드', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'S', name: '티거', location: '레이크랜드', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'SS', name: '면죄된 폭동', location: '레이크랜드', coordinate: '( 23.9, 22.1 )', drop: '&nbsp'}
    ],
    The_Raktika_Greatwood: [
        {level: '74', hunt: true, name: '투구딱정벌레', location: '라케티카 대삼림', coordinate: '( 16.3, 33.9 )', drop: '&nbsp'},
        {level: '74', hunt: true, name: '흡혈덩굴', location: '라케티카 대삼림', coordinate: '( 16.3, 33.9 )', drop: '<a href=\'https://ff14.tar.to/item/list/?redirect=true&quick-search-option=item&keyword=%ED%9D%A1%ED%98%88%EB%8D%A9%EA%B5%B4+%EC%88%98%EC%95%A1\' id=\'drop\' target=\'_blank\'>흡혈덩굴 수액</a>'},
        {level: '74', hunt: true, name: '아트로키랍토르', location: '라케티카 대삼림', coordinate: '( 11.7, 34.1 )', drop: '<a href=\'https://ff14.tar.to/item/list/?keyword=%EC%95%84%ED%8A%B8%EB%A1%9C%ED%82%A4%EB%9E%8D%ED%86%A0%EB%A5%B4+%EC%83%9D%EA%B0%80%EC%A3%BD\' id=\'drop\' target=\'_blank\'>아트로키랍토르 생가죽</a>'},
        {level: '74', hunt: true, name: '토마틀', location: '라케티카 대삼림', coordinate: '( 9.2, 36.1 )', drop: '&nbsp'},
        {level: '74', hunt: true, name: '흡혈잔', location: '라케티카 대삼림', coordinate: '( 8.4, 24.7 )', drop: '<a href=\'https://ff14.tar.to/item/list/?keyword=%ED%9D%A1%ED%98%88%EC%9E%94+%EB%8D%A9%EA%B5%B4\' id=\'drop\' target=\'_blank\'>흡혈잔 덩굴</a>'},
        {level: '74', hunt: false, name: '백발전갈', location: '라케티카 대삼림', coordinate: '( 10.2, 23.5 )', drop: '&nbsp'},
        {level: '74', hunt: false, name: '늘어둠 창술사', location: '라케티카 대삼림', coordinate: '( 7.6, 16.5 )', drop: '&nbsp'},
        {level: '74', hunt: false, name: '늘어둠 꿈술사', location: '라케티카 대삼림', coordinate: '( 7.6, 16.5 )', drop: '&nbsp'},
        {level: '74', hunt: false, name: '늘어둠 주술사', location: '라케티카 대삼림', coordinate: '( 7.6, 16.5 )', drop: '&nbsp'},
        {level: '74', hunt: true, name: '무리돼지', location: '라케티카 대삼림', coordinate: '( 13.0, 20.2 )', drop: '&nbsp'},
        {level: '74', hunt: false, name: '숲홍학', location: '라케티카 대삼림', coordinate: '( 17.6, 20.5 )', drop: '&nbsp'},
        {level: '74', hunt: false, name: '진', location: '라케티카 대삼림', coordinate: '( 15.7, 24.7 )', drop: '&nbsp'},
        {level: '75', hunt: true, name: '땅맨드릴', location: '라케티카 대삼림', coordinate: '( 33.8, 16.5 )', drop: '&nbsp'},
        {level: '75', hunt: true, name: '갈라진 롱카 상자', location: '라케티카 대삼림', coordinate: '( 29.2, 11.8 )', drop: '&nbsp'},
        {level: '75', hunt: true, name: '갈라진 롱카 가시', location: '라케티카 대삼림', coordinate: '( 25.1, 13.6 )', drop: '&nbsp'},
        {level: '75', hunt: true, name: '갈라진 롱카 인형', location: '라케티카 대삼림', coordinate: '( 25.1, 13.6 )', drop: '&nbsp'},
        {level: '75', hunt: true, name: '나무박쥐', location: '라케티카 대삼림', coordinate: '( 24.8, 7.7 )', drop: '&nbsp'},
        {level: '75', hunt: true, name: '큰숲뜸부기', location: '라케티카 대삼림', coordinate: '( 22.5, 7.4 )', drop: '&nbsp'},
        {level: '75', hunt: true, name: '타리척', location: '라케티카 대삼림', coordinate: '( 25.7, 21.6 )', drop: '&nbsp'},
        {level: '75', hunt: true, name: '물봉선화', location: '라케티카 대삼림', coordinate: '( 29.2, 22.5 )', drop: '&nbsp'},
        {level: '75', hunt: false, name: '수컷 푸른사슴', location: '라케티카 대삼림', coordinate: '( 32.8, 20.9 )', drop: '&nbsp'},
        {level: '75', hunt: false, name: '암컷 푸른사슴', location: '라케티카 대삼림', coordinate: '( 32.8, 20.9 )', drop: '&nbsp'},
        {level: '75', hunt: true, name: '메아리', location: '라케티카 대삼림', coordinate: '( 29.0, 26.3 )', drop: '&nbsp'},
        {level: '75', hunt: true, name: '기자말루크', location: '라케티카 대삼림', coordinate: '( 29.0, 26.3 )', drop: '&nbsp'},
        {level: '75', hunt: true, name: '카라칼', location: '라케티카 대삼림', coordinate: '( 25.3, 30.2 )', drop: '&nbsp'},
        {level: '80', hunt: 'B', name: '지능계발자', location: '라케티카 대삼림', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'B', name: '파차마마', location: '라케티카 대삼림', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'T', name: '면죄된 험담', location: '라케티카 대삼림', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'A', name: '숲원인', location: '라케티카 대삼림', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'A', name: '수파이', location: '라케티카 대삼림', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'S', name: '이쉬타브', location: '라케티카 대삼림', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'SS', name: '면죄된 폭동', location: '라케티카 대삼림', coordinate: '( 24.4, 37.6 )', drop: '&nbsp'},
    ],
    Il_Mheg: [
        {level: '72', hunt: true, name: '에케보어', location: '일 메그', coordinate: '( 22.2, 35.4 )', drop: '&nbsp'},
        {level: '72', hunt: true, name: '장미곰', location: '일 메그', coordinate: '( 22.2, 35.4 )', drop: '&nbsp'},
        {level: '72', hunt: false, name: '운디네', location: '일 메그', coordinate: '( 21.6, 28.9 )', drop: '&nbsp'},
        {level: '72', hunt: true, name: '꽃바구니', location: '일 메그', coordinate: '( 8.5, 31.3 )', drop: '&nbsp'},
        {level: '72', hunt: false, name: '사미아드', location: '일 메그', coordinate: '( 11.5, 36.6 )', drop: '&nbsp'},
        {level: '72', hunt: true, name: '에다인나방', location: '일 메그', coordinate: '( 11.0, 27.1 )', drop: '&nbsp'},
        {level: '72', hunt: true, name: '정원 아네모네', location: '일 메그', coordinate: '( 13.3, 23.3 )', drop: '&nbsp'},
        {level: '72', hunt: false, name: '핏빛 모르포', location: '일 메그', coordinate: '( 7.6, 23.3 )', drop: '&nbsp'},
        {level: '72', hunt: false, name: '보라 모르포', location: '일 메그', coordinate: '( 7.6, 23.3 )', drop: '&nbsp'},
        {level: '72', hunt: true, name: '왕잠자리', location: '일 메그', coordinate: '( 8.5, 18.9 )', drop: '&nbsp'},
        {level: '72', hunt: true, name: '살인벌', location: '일 메그', coordinate: '( 9.0, 15.0 )', drop: '&nbsp'},
        {level: '73', hunt: true, name: '마녀풀', location: '일 메그', coordinate: '( 10.5, 13.0 )', drop: '&nbsp'},
        {level: '73', hunt: true, name: '이끼버섯', location: '일 메그', coordinate: '( 21.1, 8.3 )', drop: '&nbsp'},
        {level: '73', hunt: true, name: '오색청해', location: '일 메그', coordinate: '( 24.6, 9.2 )', drop: '<a href=\'https://ff14.tar.to/item/list/?keyword=%EC%98%A4%EC%83%89%EC%B2%AD%ED%95%B4+%EC%95%8C\' id=\'drop\' target=\'_blank\'>오색청해 알</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EC%98%A4%EC%83%89%EC%B2%AD%ED%95%B4+%EA%B9%83%ED%84%B8\' id=\'drop\' target=\'_blank\'>오색청해 깃털</a>'},
        {level: '73', hunt: true, name: '나무인간', location: '일 메그', coordinate: '( 31.9, 5.5 )', drop: '&nbsp'},
        {level: '73', hunt: true, name: '정원 늑대개', location: '일 메그', coordinate: '( 31.9, 5.5 )', drop: '&nbsp'},
        {level: '73', hunt: true, name: '토끼꼬리', location: '일 메그', coordinate: '( 31.8, 10.6 )', drop: '&nbsp'},
        {level: '73', hunt: true, name: '어린 에이비스', location: '일 메그', coordinate: '( 31.8, 10.6 )', drop: '&nbsp'},
        {level: '73', hunt: true, name: '정원 포크시', location: '일 메그', coordinate: '( 30.9, 14.0 )', drop: '&nbsp'},
        {level: '73', hunt: false, name: '응 모우 도기술사', location: '일 메그', coordinate: '( 32.1, 18.7 )', drop: '&nbsp'},
        {level: '73', hunt: false, name: '응 모우 버섯술사', location: '일 메그', coordinate: '( 32.1, 18.7 )', drop: '&nbsp'},
        {level: '73', hunt: true, name: '초록 날장지뱀', location: '일 메그', coordinate: '( 29.2, 13.6 )', drop: '<a href=\'https://ff14.tar.to/item/list/?keyword=%EC%B4%88%EB%A1%9D+%EB%82%A0%EC%9E%A5%EC%A7%80%EB%B1%80+%EC%83%9D%EA%B0%80%EC%A3%BD\' id=\'drop\' target=\'_blank\'>초록 날장지뱀 생가죽</a>'},
        {level: '73', hunt: true, name: '푸카', location: '일 메그', coordinate: '( 19.5, 15.5 )', drop: '&nbsp'},
        {level: '80', hunt: 'B', name: '도모보이', location: '일 메그', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'B', name: '불팡구에', location: '일 메그', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'T', name: '면죄된 험담', location: '일 메그', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'A', name: '진흙인간', location: '일 메그', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'A', name: '폴디아', location: '일 메그', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'S', name: '아글라오페', location: '일 메그', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'SS', name: '면죄된 폭동', location: '일 메그', coordinate: '( 13.4, 22.8 )', drop: '&nbsp'},
    ],
    Kholusia: [
        {level: '70', hunt: true, name: '홉고블린', location: '콜루시아 섬', coordinate: '( 35.5, 30.2 )', drop: '&nbsp'},
        {level: '70', hunt: true, name: '채찍꼬리 도마뱀', location: '콜루시아 섬', coordinate: '( 32.5, 26.7 )', drop: '&nbsp'},
        {level: '70', hunt: true, name: '마울타쉬', location: '콜루시아 섬', coordinate: '( 32.5, 26.7 )', drop: '&nbsp'},
        {level: '70', hunt: true, name: '콜루시아 이구아나', location: '콜루시아 섬', coordinate: '( 28.5, 30.6 )', drop: '&nbsp'},
        {level: '70', hunt: true, name: '섬늑대', location: '콜루시아 섬', coordinate: '( 24.1, 24.5 )', drop: '<a href=\'https://ff14.tar.to/item/list/?keyword=%EC%84%AC%EB%8A%91%EB%8C%80+%EC%97%84%EB%8B%88\' id=\'drop\' target=\'_blank\'>섬늑대 엄니</a>'},
        {level: '70', hunt: true, name: '싹넝쿨', location: '콜루시아 섬', coordinate: '( 21.5, 31.1 )', drop: '&nbsp'},
        {level: '70', hunt: true, name: '트라고판', location: '콜루시아 섬', coordinate: '( 21.5, 31.1 )', drop: '&nbsp'},
        {level: '70', hunt: true, name: '나무눈', location: '콜루시아 섬', coordinate: '( 16.9, 25.9 )', drop: '&nbsp'},
        {level: '70', hunt: true, name: '섬뜸부기', location: '콜루시아 섬', coordinate: '( 16.9, 25.9 )', drop: '<a href=\'https://ff14.tar.to/item/list/?keyword=%EB%9C%B8%EB%B6%80%EA%B8%B0+%EA%B0%80%EC%8A%B4%EC%82%B4\' id=\'drop\' target=\'_blank\'>뜸부기 가슴살</a>'},
        {level: '70', hunt: false, name: '투칼리브리', location: '콜루시아 섬', coordinate: '( 15.9, 37.1 )', drop: '&nbsp'},
        {level: '70', hunt: true, name: '저지대 히솝', location: '콜루시아 섬', coordinate: '( 10.4, 29.6 )', drop: '&nbsp'},
        {level: '70', hunt: true, name: '콜루시아 들소', location: '콜루시아 섬', coordinate: '( 10.4, 29.6 )', drop: '&nbsp'},
        {level: '70', hunt: true, name: '왕집게', location: '콜루시아 섬', coordinate: '( 7.3, 32.8 )', drop: '&nbsp'},
        {level: '78', hunt: true, name: '잔돌 노움', location: '콜루시아 섬', coordinate: '( 8.6, 18.4 )', drop: '&nbsp'},
        {level: '78', hunt: true, name: '고장난 탈로스', location: '콜루시아 섬', coordinate: '( 15.9, 19.8 )', drop: '&nbsp'},
        {level: '78', hunt: true, name: '사이카니아', location: '콜루시아 섬', coordinate: '( 11.3, 15.8 )', drop: '&nbsp'},
        {level: '78', hunt: true, name: '훌두', location: '콜루시아 섬', coordinate: '( 11.3, 15.8 )', drop: '&nbsp'},
        {level: '78', hunt: true, name: '절벽날개', location: '콜루시아 섬', coordinate: '( 15.0, 10.1 )', drop: '&nbsp'},
        {level: '78', hunt: true, name: '금속회', location: '콜루시아 섬', coordinate: '( 18.0, 8.1 )', drop: '&nbsp'},
        {level: '78', hunt: true, name: '굴그누', location: '콜루시아 섬', coordinate: '( 21.0, 8.7 )', drop: '&nbsp'},
        {level: '78', hunt: true, name: '고지대 히솝', location: '콜루시아 섬', coordinate: '( 23.0, 15.5 )', drop: '&nbsp'},
        {level: '78', hunt: true, name: '고지대 이구아나', location: '콜루시아 섬', coordinate: '( 25.4, 17.3 )', drop: '&nbsp'},
        {level: '78', hunt: true, name: '절벽두더지', location: '콜루시아 섬', coordinate: '( 27.6, 11.3 )', drop: '&nbsp'},
        {level: '78', hunt: false, name: '홉고블린 경비', location: '콜루시아 섬', coordinate: '( 25.8, 10.5 )', drop: '&nbsp'},
        {level: '78', hunt: true, name: '드워프 자동인형', location: '콜루시아 섬', coordinate: '( 31.7, 18.9 )', drop: '&nbsp'},
        {level: '78', hunt: false, name: '굴그 노커', location: '콜루시아 섬', coordinate: '( 33.1, 14.0 )', drop: '&nbsp'},
        {level: '78', hunt: true, name: '유황 비르겐', location: '콜루시아 섬', coordinate: '( 34.9, 10.4 )', drop: '&nbsp'},
        {level: '80', hunt: 'B', name: '깡다구', location: '콜루시아 섬', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'B', name: '콕시그뤼', location: '콜루시아 섬', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'T', name: '면죄된 험담', location: '콜루시아 섬', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'A', name: '후라칸', location: '콜루시아 섬', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'A', name: '작은 살인자', location: '콜루시아 섬', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'S', name: '면죄된 현학', location: '콜루시아 섬', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'SS', name: '면죄된 폭동', location: '콜루시아 섬', coordinate: '( 35.0, 10.3 )', drop: '&nbsp'},
    ],
    The_Tempest: [
        {level: '79', hunt: true, name: '모르고우르', location: '템페스트', coordinate: '( 32.2, 21.7 )', drop: '&nbsp'},
        {level: '79', hunt: true, name: '삼엽충', location: '템페스트', coordinate: '( 35.5, 21.1 )', drop: '&nbsp'},
        {level: '79', hunt: true, name: '암피스바에나', location: '템페스트', coordinate: '( 36.0, 11.6 )', drop: '&nbsp'},
        {level: '79', hunt: true, name: '다곤', location: '템페스트', coordinate: '( 29.6, 14.0 )', drop: '&nbsp'},
        {level: '79', hunt: true, name: '템페스트 바다제비', location: '템페스트', coordinate: '( 28.3, 16.5 )', drop: '<a href=\'https://ff14.tar.to/item/list/?keyword=%EB%B0%94%EB%8B%A4%EC%A0%9C%EB%B9%84+%EC%83%9D%EA%B0%80%EC%A3%BD\' id=\'drop\' target=\'_blank\'>바다제비 생가죽</a>'},
        {level: '79', hunt: true, name: '수영게', location: '템페스트', coordinate: '( 37.5, 7.1 )', drop: '&nbsp'},
        {level: '79', hunt: false, name: '므뉘리', location: '템페스트', coordinate: '( 30.9, 8.8 )', drop: '&nbsp'},
        {level: '79', hunt: true, name: '클리오니드', location: '템페스트', coordinate: '( 27.4, 5.2 )', drop: '&nbsp'},
        {level: '79', hunt: true, name: '심해 거머리', location: '템페스트', coordinate: '( 27.4, 5.2 )', drop: '&nbsp'},
        {level: '79', hunt: true, name: '바다 젤라틴', location: '템페스트', coordinate: '( 25.5, 9.2 )', drop: '&nbsp'},
        {level: '79', hunt: true, name: '히드라충류', location: '템페스트', coordinate: '( 18.9, 8.4 )', drop: '<a href=\'https://ff14.tar.to/item/list/?keyword=%ED%9E%88%EB%93%9C%EB%9D%BC%EC%B6%A9%EB%A5%98+%EA%B0%93\' id=\'drop\' target=\'_blank\'>히드라충류 갓</a>'},
        {level: '79', hunt: false, name: '가자미파 격투사', location: '템페스트', coordinate: '( 11.1, 9.2 )', drop: '&nbsp'},
        {level: '79', hunt: false, name: '가자미파 점쟁이', location: '템페스트', coordinate: '( 11.1, 9.2 )', drop: '&nbsp'},
        {level: '79', hunt: false, name: '가자미파 작살꾼', location: '템페스트', coordinate: '( 11.1, 9.2 )', drop: '&nbsp'},
        {level: '79', hunt: false, name: '사마귀새우', location: '템페스트', coordinate: '( 16.7, 11.1 )', drop: '&nbsp'},
        {level: '79', hunt: true, name: '바다 아네모네', location: '템페스트', coordinate: '( 24.1, 18.5 )', drop: '&nbsp'},
        {level: '79', hunt: false, name: '창가오리', location: '템페스트', coordinate: '( 13.6, 16.6 )', drop: '&nbsp'},
        {level: '79', hunt: false, name: '성게어', location: '템페스트', coordinate: '( 9.6, 16.3 )', drop: '&nbsp'},
        {level: '79', hunt: false, name: '단바니아', location: '템페스트', coordinate: '( 6.0, 13.9 )', drop: '&nbsp'},
        {level: '79', hunt: false, name: '노플리우스', location: '템페스트', coordinate: '( 30.2, 15.8, -2.3 )', drop: '&nbsp'},
        {level: '79', hunt: true, name: '컵푸딩', location: '템페스트', coordinate: '( 22.9, 31.4 )', drop: '<a href=\'https://ff14.tar.to/item/list/?keyword=%EC%BB%B5%ED%91%B8%EB%94%A9+%EC%82%B4\' id=\'drop\' target=\'_blank\'>컵푸딩 살</a>'},
        {level: '80', hunt: 'B', name: '부사제게', location: '템페스트', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'B', name: '맨손의 기우쉬 아스', location: '템페스트', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'T', name: '면죄된 험담', location: '템페스트', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'A', name: '루살카', location: '템페스트', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'A', name: '바알', location: '템페스트', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'S', name: '구니트', location: '템페스트', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '80', hunt: 'SS', name: '면죄된 폭동', location: '템페스트', coordinate: '( 12.7, 21.9 )', drop: '&nbsp'},
    ],
    The_Fringes: [
        {level: '60', hunt: true, name: '례쉬', location: '기라바니아 변방지대', coordinate: '( 11.0, 13.6 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19930\' id=\'drop\' target=\'_blank\'>너도밤나무 원목</a>'},
        {level: '60', hunt: true, name: '가젤매', location: '기라바니아 변방지대', coordinate: '( 11.8, 13.3 )', drop: '&nbsp'},
        {level: '60', hunt: true, name: '사프리아', location: '기라바니아 변방지대', coordinate: '( 10.0, 14.6 )', drop: '&nbsp'},
        {level: '60', hunt: true, name: '벨로디나 사르코수쿠스', location: '기라바니아 변방지대', coordinate: '( 18.0, 11.8 )', drop: '&nbsp'},
        {level: '60', hunt: true, name: '작은 가가나', location: '기라바니아 변방지대', coordinate: '( 21.9, 10.6 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19877\' id=\'drop\' target=\'_blank\'>가가나 알</a>'},
        {level: '60', hunt: true, name: '물레거미', location: '기라바니아 변방지대', coordinate: '( 21.9, 10.6 )', drop: '&nbsp'},
        {level: '60', hunt: true, name: '포퍼', location: '기라바니아 변방지대', coordinate: '( 21.8, 13.2 )', drop: '&nbsp'},
        {level: '60', hunt: false, name: '먼지 다라', location: '기라바니아 변방지대', coordinate: '( 26.4, 13.8 )', drop: '&nbsp'},
        {level: '60', hunt: true, name: '차디찬 브후트', location: '기라바니아 변방지대', coordinate: '( 25.2, 16.0 )', drop: '&nbsp'},
        {level: '60', hunt: true, name: '벨로디나 푸길', location: '기라바니아 변방지대', coordinate: '( 27.9, 15.8 )', drop: '&nbsp'},
        {level: '61', hunt: true, name: '산악 회색곰', location: '기라바니아 변방지대', coordinate: '( 10.7, 17.5 )', drop: '&nbsp'},
        {level: '61', hunt: true, name: '이끼이끼', location: '기라바니아 변방지대', coordinate: '( 11.6, 18.0 )', drop: '&nbsp'},
        {level: '61', hunt: false, name: '물잠자리', location: '기라바니아 변방지대', coordinate: '( 11.6, 22.8 )', drop: '&nbsp'},
        {level: '61', hunt: true, name: '디아카', location: '기라바니아 변방지대', coordinate: '( 10.9, 27.6 )', drop: '&nbsp'},
        {level: '61', hunt: true, name: '기러기아귀', location: '기라바니아 변방지대', coordinate: '( 10.3, 28.5 )', drop: '&nbsp'},
        {level: '61', hunt: false, name: '개미귀신 추격자', location: '기라바니아 변방지대', coordinate: '( 15.4, 23.5 )', drop: '&nbsp'},
        {level: '67', hunt: false, name: '가가나', location: '기라바니아 변방지대', coordinate: '( 28.2, 17.1 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19877\' id=\'drop\' target=\'_blank\'>가가나 알</a>'},
        {level: '67', hunt: true, name: '텔레오케라스', location: '기라바니아 변방지대', coordinate: '( 28.7, 23.5 )', drop: '&nbsp'},
        {level: '67', hunt: false, name: '개미귀신 추적자', location: '기라바니아 변방지대', coordinate: '( 30.4, 27.8 )', drop: '&nbsp'},
        {level: '67', hunt: false, name: '개미귀신 잠복자', location: '기라바니아 변방지대', coordinate: '( 31.5, 28.2 )', drop: '&nbsp'},
        {level: '67', hunt: true, name: '가젤', location: '기라바니아 변방지대', coordinate: '( 25.7, 29.2 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19920\' id=\'drop\' target=\'_blank\'>가젤 뿔</a><br><a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=20003\' id=\'drop\' target=\'_blank\'>가젤 생가죽</a>'},
        {level: '67', hunt: true, name: '칼리아나 크샤트리아', location: '기라바니아 변방지대', coordinate: '( 34.3, 25.3 )', drop: '&nbsp'},
        {level: '67', hunt: true, name: '칼리아나 수드라', location: '기라바니아 변방지대', coordinate: '( 34.3, 25.3 )', drop: '&nbsp'},
        {level: '67', hunt: true, name: '칼리아나 브라만', location: '기라바니아 변방지대', coordinate: '( 34.3, 25.3 )', drop: '&nbsp'},
        {level: '67', hunt: true, name: '성스러운 마리드', location: '기라바니아 변방지대', coordinate: '( 34.3, 25.3 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=20002\' id=\'drop\' target=\'_blank\'>마리드 생가죽</a>'},
        {level: '70', hunt: 'B', name: '오젤룸', location: '기라바니아 변방지대', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'B', name: '땅거미의 야미니', location: '기라바니아 변방지대', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'A', name: '오르쿠스', location: '기라바니아 변방지대', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'A', name: '얼', location: '기라바니아 변방지대', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'S', name: '우담바라', location: '기라바니아 변방지대', coordinate: '지도 참조', drop: '&nbsp'}
    ],
    The_Peaks: [
        {level: '60', hunt: true, name: '먼지 아닐라', location: '기라바니아 산악지대', coordinate: '( 21.6, 13.6 )', drop: '&nbsp'},
        {level: '60', hunt: false, name: '키키룬 고기냠냠이', location: '기라바니아 산악지대', coordinate: '( 17.3, 15.9 )', drop: '&nbsp'},
        {level: '60', hunt: true, name: '반짝나비', location: '기라바니아 산악지대', coordinate: '( 13.2, 10.3 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19922\' id=\'drop\' target=\'_blank\'>비늘가루</a>'},
        {level: '60', hunt: true, name: '기라바니아 뿔부리', location: '기라바니아 산악지대', coordinate: '( 10.1, 7.5 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19874\' id=\'drop\' target=\'_blank\'>붉은뿔부리 가슴살</a>'},
        {level: '60', hunt: true, name: '큰메뚜기', location: '기라바니아 산악지대', coordinate: '( 20.2, 7.4 )', drop: '&nbsp'},
        {level: '60', hunt: true, name: '핏빛날개나방', location: '기라바니아 산악지대', coordinate: '( 17.2, 11.0 )', drop: '&nbsp'},
        {level: '61', hunt: true, name: '바위발톱', location: '기라바니아 산악지대', coordinate: '( 26.5, 8.2 )', drop: '&nbsp'},
        {level: '61', hunt: true, name: '기라바니아 쇠똥구리', location: '기라바니아 산악지대', coordinate: '( 25.0, 13.8 )', drop: '&nbsp'},
        {level: '61', hunt: false, name: '키키룬 고기싹둑이', location: '기라바니아 산악지대', coordinate: '( 26.7, 20.6 )', drop: '&nbsp'},
        {level: '61', hunt: true, name: '루드수드', location: '기라바니아 산악지대', coordinate: '( 31.8, 9.0 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19919\' id=\'drop\' target=\'_blank\'>무드수드 뿔</a>'},
        {level: '61', hunt: true, name: '대리석 요결석', location: '기라바니아 산악지대', coordinate: '( 35.5, 8.9 )', drop: '&nbsp'},
        {level: '68', hunt: false, name: '높은날개 큰메뚜기', location: '기라바니아 산악지대', coordinate: '( 14.0, 35.8 )', drop: '&nbsp'},
        {level: '68', hunt: true, name: '판테라', location: '기라바니아 산악지대', coordinate: '( 12.4, 31.1 )', drop: '&nbsp'},
        {level: '68', hunt: true, name: '콩가마토', location: '기라바니아 산악지대', coordinate: '( 14.6, 25.2 )', drop: '&nbsp'},
        {level: '68', hunt: true, name: '순종 그리핀', location: '기라바니아 산악지대', coordinate: '( 25.2, 24.7 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=20004\' id=\'drop\' target=\'_blank\'>순종 그리핀 생가죽</a>'},
        {level: '68', hunt: true, name: '잠멜', location: '기라바니아 산악지대', coordinate: '( 25.7, 29.7 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19875\' id=\'drop\' target=\'_blank\'>잠멜 고기</a>'},
        {level: '68', hunt: true, name: '고원 에루카', location: '기라바니아 산악지대', coordinate: '( 24.3, 33.6 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19989\' id=\'drop\' target=\'_blank\'>쌍고치</a>'},
        {level: '70', hunt: 'B', name: '부카부', location: '기라바니아 산악지대', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'B', name: '독사의 종복', location: '기라바니아 산악지대', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'A', name: '보크스타인', location: '기라바니아 산악지대', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'A', name: '아크라부아멜루', location: '기라바니아 산악지대', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'S', name: '해골거미', location: '기라바니아 산악지대', coordinate: '지도 참조', drop: '&nbsp'}
    ],
    The_Lochs: [
        {level: '69', hunt: true, name: '칼루크', location: '기라바니아 호반지대', coordinate: '( 10.8, 17.5 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19933\' id=\'drop\' target=\'_blank\'>느티나무 원목</a>'},
        {level: '69', hunt: true, name: '로흐 거머리', location: '기라바니아 호반지대', coordinate: '( 17.2, 14.6 )', drop: '&nbsp'},
        {level: '69', hunt: true, name: '로흐 낭카', location: '기라바니아 호반지대', coordinate: '( 17.4, 16.1 )', drop: '&nbsp'},
        {level: '69', hunt: true, name: '켈로네', location: '기라바니아 호반지대', coordinate: '( 26.2, 14.4 )', drop: '&nbsp'},
        {level: '69', hunt: true, name: '아발라시아 미노타우로스', location: '기라바니아 호반지대', coordinate: '( 29.0, 9.1 )', drop: '&nbsp'},
        {level: '69', hunt: true, name: '근위 브후트', location: '기라바니아 호반지대', coordinate: '( 24.4, 9.2 )', drop: '&nbsp'},
        {level: '69', hunt: true, name: '그림자요괴', location: '기라바니아 호반지대', coordinate: '( 18.5, 7.3 )', drop: '&nbsp'},
        {level: '69', hunt: true, name: '땅을 기는 에딜라', location: '기라바니아 호반지대', coordinate: '( 7.6, 8.0 )', drop: '&nbsp'},
        {level: '69', hunt: true, name: '염호 아닐라', location: '기라바니아 호반지대', coordinate: '( 5.0, 15.6 )', drop: '&nbsp'},
        {level: '69', hunt: true, name: '소브란', location: '기라바니아 호반지대', coordinate: '( 15.1, 22.7 )', drop: '&nbsp'},
        {level: '69', hunt: false, name: '염호 다라', location: '기라바니아 호반지대', coordinate: '( 13.2, 29.7 )', drop: '&nbsp'},
        {level: '69', hunt: true, name: '아바돈', location: '기라바니아 호반지대', coordinate: '( 19.1, 31.9 )', drop: '&nbsp'},
        {level: '69', hunt: true, name: '베파르', location: '기라바니아 호반지대', coordinate: '( 24.2, 30.3 )', drop: '&nbsp'},
        {level: '69', hunt: true, name: '포배드', location: '기라바니아 호반지대', coordinate: '( 23.3, 25.9 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=5518\' id=\'drop\' target=\'_blank\'>암염</a>'},
        {level: '69', hunt: true, name: '드루바', location: '기라바니아 호반지대', coordinate: '( 22.8, 22.9 )', drop: '&nbsp'},
        {level: '69', hunt: true, name: '탈라시나', location: '기라바니아 호반지대', coordinate: '( 19.6, 26.1 )', drop: '&nbsp'},
        {level: '69', hunt: true, name: '산악 찰흙야수', location: '기라바니아 호반지대', coordinate: '( 5.6, 26.3 )', drop: '&nbsp'},
        {level: '70', hunt: 'B', name: '마네스', location: '기라바니아 호반지대', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'B', name: '키와', location: '기라바니아 호반지대', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'A', name: '마히샤', location: '기라바니아 호반지대', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'A', name: '루미나레', location: '기라바니아 호반지대', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'S', name: '빛과 소금', location: '기라바니아 호반지대', coordinate: '지도 참조', drop: '&nbsp'}
    ],
    Ruby_Sea: [
        {level: '62', hunt: true, name: '해마', location: '홍옥해', coordinate: '( 30.0, 38.3 )', drop: '&nbsp'},
        {level: '62', hunt: true, name: '가시봄', location: '홍옥해', coordinate: '( 30.0, 38.3 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19923\' id=\'drop\' target=\'_blank\'>가시봄 가시</a>'},
        {level: '62', hunt: true, name: '가사메', location: '홍옥해', coordinate: '( 25.9, 36.6 )', drop: '&nbsp'},
        {level: '62', hunt: true, name: '지옥 아날라', location: '홍옥해', coordinate: '( 25.9, 36.6 )', drop: '&nbsp'},
        {level: '62', hunt: true, name: '날상어', location: '홍옥해', coordinate: '( 29.0, 31.5 )', drop: '&nbsp'},
        {level: '62', hunt: true, name: '귀신물범', location: '홍옥해', coordinate: '( 18.5, 10.3 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=20000\' id=\'drop\' target=\'_blank\'>귀신물범 생가죽</a>'},
        {level: '62', hunt: true, name: '시라누이', location: '홍옥해', coordinate: '( 18.6, 7.2 )', drop: '&nbsp'},
        {level: '62', hunt: true, name: '큰바다뱀', location: '홍옥해', coordinate: '( 30.2, 7.7 )', drop: '&nbsp'},
        {level: '62', hunt: true, name: '산호게', location: '홍옥해', coordinate: '( 32.3, 3.7 )', drop: '&nbsp'},
        {level: '62', hunt: true, name: '철갑게', location: '홍옥해', coordinate: '( 35.6, 21.6 )', drop: '&nbsp'},
        {level: '63', hunt: true, name: '아파', location: '홍옥해', coordinate: '( 17.7, 35.3 )', drop: '&nbsp'},
        {level: '63', hunt: true, name: '줄가오리', location: '홍옥해', coordinate: '( 8.2, 26.6 )', drop: '&nbsp'},
        {level: '63', hunt: true, name: '붉은등 부칸', location: '홍옥해', coordinate: '( 8.2, 26.6 )', drop: '&nbsp'},
        {level: '63', hunt: true, name: '붉은등 효우에', location: '홍옥해', coordinate: '( 8.2, 26.6 )', drop: '&nbsp'},
        {level: '63', hunt: true, name: '붉은등 혼칸', location: '홍옥해', coordinate: '( 8.2, 26.6 )', drop: '&nbsp'},
        {level: '63', hunt: false, name: '거단', location: '홍옥해', coordinate: '( 8.5, 6.2 )', drop: '&nbsp'},
        {level: '63', hunt: true, name: '꿈고둥', location: '홍옥해', coordinate: '( 25.3, 26.9 )', drop: '&nbsp'},
        {level: '63', hunt: true, name: '꿈고둥 알맹이', location: '홍옥해', coordinate: '( 25.3, 26.9 )', drop: '&nbsp'},
        {level: '63', hunt: true, name: '붉은뿔부리', location: '홍옥해', coordinate: '( 34.3, 23.0 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19874\' id=\'drop\' target=\'_blank\'>붉은뿔부리 가슴살</a>'},
        {level: '70', hunt: 'B', name: '검호 가우키', location: '홍옥해', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'B', name: '우부메', location: '홍옥해', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'A', name: '선박 유령', location: '홍옥해', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'A', name: '귀신 꿈고둥', location: '홍옥해', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'S', name: '오키나', location: '홍옥해', coordinate: '지도 참조', drop: '&nbsp'}
    ],
    YANXIA: [
        {level: '64', hunt: true, name: '미노비', location: '얀샤', coordinate: '( 33.1, 17.2 )', drop: '&nbsp'},
        {level: '64', hunt: false, name: '얀샤 호랑이', location: '얀샤', coordinate: '( 37.5, 15.9 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=20001\' id=\'drop\' target=\'_blank\'>호랑이 생가죽</a>'},
        {level: '64', hunt: true, name: '장수풍뎅이', location: '얀샤', coordinate: '( 31.0, 22.6 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19924\' id=\'drop\' target=\'_blank\'>장수풍뎅이 갑각</a>'},
        {level: '64', hunt: true, name: '무이강 붉은뿔부리', location: '얀샤', coordinate: '( 31.7, 26.1 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19874\' id=\'drop\' target=\'_blank\'>붉은뿔부리 가슴살</a>'},
        {level: '64', hunt: false, name: '도마 족제비', location: '얀샤', coordinate: '( 33.3, 29.8 )', drop: '&nbsp'},
        {level: '64', hunt: true, name: '물뱀', location: '얀샤', coordinate: '( 24.4, 26.3 )', drop: '&nbsp'},
        {level: '64', hunt: true, name: '인랑족 칼잡이', location: '얀샤', coordinate: '( 23.9, 28.9 )', drop: '&nbsp'},
        {level: '64', hunt: true, name: '인랑족 활잡이', location: '얀샤', coordinate: '( 23.9, 28.9 )', drop: '&nbsp'},
        {level: '64', hunt: true, name: '인랑족 창잡이', location: '얀샤', coordinate: '( 23.9, 28.9 )', drop: '&nbsp'},
        {level: '64', hunt: true, name: '바나라', location: '얀샤', coordinate: '( 23.4, 30.8 )', drop: '&nbsp'},
        {level: '64', hunt: true, name: '긴팔이', location: '얀샤', coordinate: '( 24.9, 33.4 )', drop: '&nbsp'},
        {level: '64', hunt: true, name: '타오취엔', location: '얀샤', coordinate: '( 30.5, 35.1 )', drop: '&nbsp'},
        {level: '64', hunt: false, name: '겐스이 아파', location: '얀샤', coordinate: '( 20.9, 33.8 )', drop: '&nbsp'},
        {level: '64', hunt: true, name: '팔방조', location: '얀샤', coordinate: '( 18.1, 31.3 )', drop: '&nbsp'},
        {level: '64', hunt: true, name: '코자', location: '얀샤', coordinate: '( 14.8, 29.6 )', drop: '&nbsp'},
        {level: '67', hunt: true, name: '무지개 호랑이', location: '얀샤', coordinate: '( 27.4, 12.1 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=20001\' id=\'drop\' target=\'_blank\'>호랑이 생가죽</a>'},
        {level: '67', hunt: true, name: '에비스 나마즈오', location: '얀샤', coordinate: '( 29.0, 7.9 )', drop: '&nbsp'},
        {level: '67', hunt: false, name: '흰날개 붉은뿔부리', location: '얀샤', coordinate: '( 20.2, 13.6 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19874\' id=\'drop\' target=\'_blank\'>붉은뿔부리 가슴살</a>'},
        {level: '67', hunt: true, name: '마가츠 코자', location: '얀샤', coordinate: '( 18.7, 10.5 )', drop: '&nbsp'},
        {level: '67', hunt: true, name: '마가츠 키요후사', location: '얀샤', coordinate: '( 18.7, 10.5 )', drop: '&nbsp'},
        {level: '70', hunt: 'B', name: '뇌격의 교라이', location: '얀샤', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'B', name: '데이다라', location: '얀샤', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'A', name: '가자수라', location: '얀샤', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'A', name: '앙가다', location: '얀샤', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'S', name: '감마', location: '얀샤', coordinate: '지도 참조', drop: '&nbsp'}
    ],
    AZIM_STEPPE: [
        {level: '65', hunt: true, name: '긴털들소', location: '아짐 대초원', coordinate: '( 30.2, 30.1 )', drop: 
        '<a href=\'https://ff14.tar.to/item/list/?keyword=%EA%B8%B4%ED%84%B8%EB%93%A4%EC%86%8C+%EC%95%9E%EB%8B%A4%EB%A6%BF%EC%82%B4\' id=\'drop\' target=\'_blank\'>긴털들소 앞다릿살</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EA%B8%B4%ED%84%B8%EB%93%A4%EC%86%8C+%EB%BF%94\' id=\'drop\' target=\'_blank\'>긴털들소 뿔</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EC%B4%88%EC%9B%90+%EC%9A%B0%EC%9C%A0\' id=\'drop\' target=\'_blank\'>초원 우유</a>'},
        {level: '65', hunt: true, name: '마타마타', location: '아짐 대초원', coordinate: '( 23.6, 13.6 )', drop: '&nbsp'},
        {level: '65', hunt: true, name: '훈 촐로오', location: '아짐 대초원', coordinate: '( 13.0, 14.0 )', drop: '&nbsp'},
        {level: '65', hunt: true, name: '모오 쇼보오', location: '아짐 대초원', coordinate: '( 23.7, 10.5 )', drop: '&nbsp'},
        {level: '65', hunt: true, name: '매머드', location: '아짐 대초원', coordinate: '( 28.9, 17.5 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=20002\' id=\'drop\' target=\'_blank\'>마리드 생가죽</a>'},
        {level: '65', hunt: true, name: '풀볼', location: '아짐 대초원', coordinate: '( 32.8, 21.0 )', drop: '&nbsp'},
        {level: '65', hunt: true, name: '초원 거단', location: '아짐 대초원', coordinate: '( 34.4, 23.8 )', drop: '&nbsp'},
        {level: '65', hunt: true, name: '초원 긴팔이', location: '아짐 대초원', coordinate: '( 28.8, 28.1 )', drop: '&nbsp'},
        {level: '65', hunt: true, name: '할가이', location: '아짐 대초원', coordinate: '( 21.4, 18.6 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19985\' id=\'drop\' target=\'_blank\'>할가이 갈기</a>'},
        {level: '66', hunt: true, name: '윙윙잠자리', location: '아짐 대초원', coordinate: '( 23.3, 31.7 )', drop: '&nbsp'},
        {level: '66', hunt: true, name: '카오츄', location: '아짐 대초원', coordinate: '( 19.9, 29.8 )', drop: '&nbsp'},
        {level: '66', hunt: true, name: '만자시리', location: '아짐 대초원', coordinate: '( 16.9, 34.2 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19986\' id=\'drop\' target=\'_blank\'>만자시리 털</a>'},
        {level: '66', hunt: false, name: '초원 아날라', location: '아짐 대초원', coordinate: '( 14.6, 30.8 )', drop: '&nbsp'},
        {level: '66', hunt: false, name: '굴로굴로', location: '아짐 대초원', coordinate: '( 13.6, 27.3 )', drop: '&nbsp'},
        {level: '66', hunt: true, name: '바르스', location: '아짐 대초원', coordinate: '( 12.0, 22.8 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=20001\' id=\'drop\' target=\'_blank\'>호랑이 생가죽</a>'},
        {level: '66', hunt: true, name: '마탕가', location: '아짐 대초원', coordinate: '( 10.0, 20.1 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=20002\' id=\'drop\' target=\'_blank\'>마리드 생가죽</a>'},
        {level: '70', hunt: 'B', name: '쿠르마', location: '아짐 대초원', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'B', name: '아스왕', location: '아짐 대초원', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'A', name: '기리메칼라', location: '아짐 대초원', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'A', name: '솜', location: '아짐 대초원', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '70', hunt: 'S', name: '오르가나', location: '아짐 대초원', coordinate: '지도 참조', drop: '&nbsp'}
    ],
    Coerthas_Western_Highlands: [
        {level: '50', hunt: true, name: '베르그투르스', location: '커르다스 서부고지', coordinate: '( 31.6, 24.3 )', drop: '&nbsp'},
        {level: '50', hunt: true, name: '산악 영양', location: '커르다스 서부고지', coordinate: '( 30.0, 32.2 )', drop: '&nbsp'},
        {level: '50', hunt: true, name: '서리 그레네이드', location: '커르다스 서부고지', coordinate: '( 28.6, 12.5 )', drop: '&nbsp'},
        {level: '50', hunt: true, name: '은빛 늑대', location: '커르다스 서부고지', coordinate: '( 26.2, 24.4 )', drop: '&nbsp'},
        {level: '50', hunt: true, name: '고지대 밀로돈', location: '커르다스 서부고지', coordinate: '( 31.7, 20.9 )', drop: '&nbsp'},
        {level: '50', hunt: true, name: '볼록눈', location: '커르다스 서부고지', coordinate: '( 30.7, 31.3 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=12628\' id=\'drop\' target=\'_blank\'>볼록눈의 눈물</a>'},
        {level: '50', hunt: false, name: '난도질 조브란', location: '커르다스 서부고지', coordinate: '( 25.2, 12.5 )', drop: '&nbsp'},
        {level: '50', hunt: true, name: '얼음풀', location: '커르다스 서부고지', coordinate: '( 23.6, 16.1 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=12637\' id=\'drop\' target=\'_blank\'>얼음풀 잎</a>'},
        {level: '50', hunt: false, name: '찬바람 달마수리', location: '커르다스 서부고지', coordinate: '( 31.2, 11.4 )', drop: '&nbsp'},
        {level: '51', hunt: true, name: '아르케오니스', location: '커르다스 서부고지', coordinate: '( 17.0, 11.8 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=12568\' id=\'drop\' target=\'_blank\'>아르케오니스 생가죽</a>'},
        {level: '51', hunt: true, name: '털복숭이 야크', location: '커르다스 서부고지', coordinate: '( 15.2, 17.1 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=12888\' id=\'drop\' target=\'_blank\'>야크 젖</a>'},
        {level: '51', hunt: true, name: '북극곰', location: '커르다스 서부고지', coordinate: '( 22.8, 21.7 )', drop: '&nbsp'},
        {level: '51', hunt: true, name: '외로운 예티', location: '커르다스 서부고지', coordinate: '( 20.1, 32.5 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=12575\' id=\'drop\' target=\'_blank\'>예티 엄니</a>'},
        {level: '51', hunt: true, name: '얼음 지휘관', location: '커르다스 서부고지', coordinate: '( 10.7, 14.5 )', drop: '&nbsp'},
        {level: '51', hunt: true, name: '젤라토', location: '커르다스 서부고지', coordinate: '( 11.6, 18.9 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=12635\' id=\'drop\' target=\'_blank\'>젤라토 살</a>'},
        {level: '51', hunt: true, name: '진물', location: '커르다스 서부고지', coordinate: '( 16.6, 20.1 )', drop: '&nbsp'},
        {level: '56', hunt: false, name: '빈드두르스', location: '커르다스 서부고지', coordinate: '( 9.6, 9.5 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=5439\' id=\'drop\' target=\'_blank\'>오거의 뿔</a>'},
        {level: '56', hunt: true, name: '내륙 투르수스', location: '커르다스 서부고지', coordinate: '( 31.6, 8.0 )', drop: '&nbsp'},
        {level: '56', hunt: false, name: '대형 아르케오니스', location: '커르다스 서부고지', coordinate: '( 35.2, 18.1 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=12568\' id=\'drop\' target=\'_blank\'>아르케오니스 생가죽</a>'},
        {level: '56', hunt: false, name: '소르베', location: '커르다스 서부고지', coordinate: '( 16.8, 26.4 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=12635\' id=\'drop\' target=\'_blank\'>젤라토 살</a>'},
        {level: '56', hunt: false, name: '점판암 예티', location: '커르다스 서부고지', coordinate: '( 25.5, 32.0 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=12575\' id=\'drop\' target=\'_blank\'>예티 엄니</a>'},
        {level: '56', hunt: false, name: '빙결 드래곤', location: '커르다스 서부고지', coordinate: '( 14.2, 23.9 )', drop: 
        '<a href=\'https://ff14.tar.to/item/list/?keyword=%EB%93%9C%EB%9E%98%EA%B3%A4+%EC%83%9D%EA%B0%80%EC%A3%BD\' id=\'drop\' target=\'_blank\'>드래곤 생가죽</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EB%93%9C%EB%9E%98%EA%B3%A4+%EC%86%A1%EA%B3%B3%EB%8B%88\' id=\'drop\' target=\'_blank\'>드래곤 송곳니</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EC%9A%A9%EC%A1%B1%EC%9D%98+%ED%94%BC\' id=\'drop\' target=\'_blank\'>용족의 피</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EB%93%9C%EB%9E%98%EA%B3%A4%EC%9D%98+%EB%B9%84%EB%8A%98\' id=\'drop\' target=\'_blank\'>드래곤의 비늘</a>'},
        {level: '56', hunt: false, name: '얼음 조브란', location: '커르다스 서부고지', coordinate: '( 15.8, 33.0 )', drop: '&nbsp'},
        {level: '60', hunt: 'B', name: '크루제', location: '커르다스 서부고지', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'B', name: '알티크', location: '커르다스 서부고지', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'A', name: '미르카', location: '커르다스 서부고지', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'A', name: '류바', location: '커르다스 서부고지', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'S', name: '카이저 베히모스', location: '커르다스 서부고지', coordinate: '지도 참조', drop: '&nbsp'}
    ],
    Sea_of_Clouds: [
        {level: '50', hunt: true, name: '오브델라', location: '아발라시아 구름바다', coordinate: '( 26.2, 33.5 )', drop: '&nbsp'},
        {level: '50', hunt: true, name: '코노돈트', location: '아발라시아 구름바다', coordinate: '( 26.2, 33.5 )', drop: '&nbsp'},
        {level: '50', hunt: true, name: '구름지렁이', location: '아발라시아 구름바다', coordinate: '( 25.8, 35.5 )', drop: '&nbsp'},
        {level: '50', hunt: true, name: '파이싸', location: '아발라시아 구름바다', coordinate: '( 21.2, 32.6 )', drop: '&nbsp'},
        {level: '50', hunt: true, name: '게일리캣', location: '아발라시아 구름바다', coordinate: '( 11.6, 33.7 )', drop: '&nbsp'},
        {level: '50', hunt: true, name: '가스토르니스', location: '아발라시아 구름바다', coordinate: '( 11.6, 33.7 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=12871\' id=\'drop\' target=\'_blank\'>가스토르니스 알</a>'},
        {level: '51', hunt: true, name: '란라이 군두', location: '아발라시아 구름바다', coordinate: '( 36.5, 24.2 )', drop: '&nbsp'},
        {level: '51', hunt: true, name: '부크라이 군두', location: '아발라시아 구름바다', coordinate: '( 36.5, 24.2 )', drop: '&nbsp'},
        {level: '51', hunt: true, name: '사누와', location: '아발라시아 구름바다', coordinate: '( 36.5, 24.2 )', drop: '&nbsp'},
        {level: '51', hunt: true, name: '나트라이 군두', location: '아발라시아 구름바다', coordinate: '( 36.5, 24.2 )', drop: '&nbsp'},
        {level: '56', hunt: false, name: '코리건', location: '아발라시아 구름바다', coordinate: '( 19.8, 28.7 )', drop: '&nbsp'},
        {level: '56', hunt: true, name: '달멜', location: '아발라시아 구름바다', coordinate: '( 18.9, 29.8 )', drop: 
        '<a href=\'https://ff14.tar.to/item/list/?keyword=%EB%8B%AC%EB%A9%9C+%EC%83%9D%EA%B0%80%EC%A3%BD\' id=\'drop\' target=\'_blank\'>달멜 생가죽</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EB%8B%AC%EB%A9%9C%EC%9D%98+%ED%83%80%EC%95%A1\' id=\'drop\' target=\'_blank\'>달멜의 타액</a><br><a href=\'https://ff14.tar.to/item/list/?redirect=true&quick-search-option=item&keyword=%EB%8B%AC%EB%A9%9C+%EA%B3%A0%EA%B8%B0\' id=\'drop\' target=\'_blank\'>달멜 고기</a>'},
        {level: '56', hunt: false, name: '교활한 파이싸', location: '아발라시아 구름바다', coordinate: '( 14.5, 30.5 )', drop: '&nbsp'},
        {level: '56', hunt: true, name: '큰뿔들소', location: '아발라시아 구름바다', coordinate: '( 11.7, 31.3 )', drop: '&nbsp'},
        {level: '57', hunt: true, name: '분두족 우상', location: '아발라시아 구름바다', coordinate: '( 18.2, 17.2 )', drop: '&nbsp'},
        {level: '57', hunt: true, name: '푸른하늘 와무라', location: '아발라시아 구름바다', coordinate: '( 9.3, 16.4 )', drop: '&nbsp'},
        {level: '57', hunt: true, name: '푸른하늘 와무라 유충', location: '아발라시아 구름바다', coordinate: '( 9.3, 16.4 )', drop: '&nbsp'},
        {level: '57', hunt: true, name: '땅지킴이', location: '아발라시아 구름바다', coordinate: '( 21.8, 13.4 )', drop: '&nbsp'},
        {level: '57', hunt: false, name: '아발라시아 솔개', location: '아발라시아 구름바다', coordinate: '( 6.5, 22.7 )', drop: '&nbsp'},
        {level: '57', hunt: true, name: '엔디미온', location: '아발라시아 구름바다', coordinate: '( 17.6, 10.2 )', drop: '&nbsp'},
        {level: '57', hunt: false, name: 'VI군단 야수투사', location: '아발라시아 구름바다', coordinate: '( 31.0, 14.5 )', drop: '&nbsp'},
        {level: '57', hunt: false, name: 'VI군단 황제기수', location: '아발라시아 구름바다', coordinate: '( 31.0, 14.5 )', drop: '&nbsp'},
        {level: '57', hunt: false, name: 'VI군단 도끼투사', location: '아발라시아 구름바다', coordinate: '( 31.0, 14.5 )', drop: '&nbsp'},
        {level: '57', hunt: false, name: 'VI군단 경보병', location: '아발라시아 구름바다', coordinate: '( 31.0, 14.5 )', drop: '&nbsp'},
        {level: '57', hunt: false, name: 'VI군단 중장투사', location: '아발라시아 구름바다', coordinate: '( 31.0, 14.5 )', drop: '&nbsp'},
        {level: '57', hunt: false, name: '사누와 분두', location: '아발라시아 구름바다', coordinate: '( 25.2, 24.8 )', drop: '&nbsp'},
        {level: '57', hunt: false, name: '부크라이 분두', location: '아발라시아 구름바다', coordinate: '( 25.2, 24.8 )', drop: '&nbsp'},
        {level: '57', hunt: false, name: '나트라이 분두', location: '아발라시아 구름바다', coordinate: '( 25.2, 24.8 )', drop: '&nbsp'},
        {level: '57', hunt: false, name: '란라이 분두', location: '아발라시아 구름바다', coordinate: '( 25.2, 24.8 )', drop: '&nbsp'},
        {level: '59', hunt: false, name: '흉내지빠귀 우상', location: '아발라시아 구름바다', coordinate: '( 13.6, 20.9 )', drop: '&nbsp'},
        {level: '59', hunt: false, name: '오사누와 분두', location: '아발라시아 구름바다', coordinate: '( 13.6, 20.9 )', drop: '&nbsp'},
        {level: '59', hunt: false, name: '부크로이 분두', location: '아발라시아 구름바다', coordinate: '( 13.6, 20.9 )', drop: '&nbsp'},
        {level: '59', hunt: false, name: '나트로이 분두', location: '아발라시아 구름바다', coordinate: '( 13.6, 20.9 )', drop: '&nbsp'},
        {level: '59', hunt: false, name: '란로이 분두', location: '아발라시아 구름바다', coordinate: '( 13.6, 20.9 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '안즈', location: '아발라시아 구름바다', coordinate: '( 21.2, 6.9 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '총총새', location: '아발라시아 구름바다', coordinate: '( 21.2, 6.9 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '차나할레', location: '아발라시아 구름바다', coordinate: '( 10.5, 26.2 )', drop: '&nbsp'},
        {level: '59', hunt: false, name: '그리핀', location: '아발라시아 구름바다', coordinate: '( 8.4, 7.9 )', drop: '<a href=\'https://ff14.tar.to/item/list/?keyword=%EA%B7%B8%EB%A6%AC%ED%95%80+%EB%B0%9C%ED%86%B1\' id=\'drop\' target=\'_blank\'>그리핀 발톱</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EA%B7%B8%EB%A6%AC%ED%95%80+%EC%83%9D%EA%B0%80%EC%A3%BD\' id=\'drop\' target=\'_blank\'>그리핀 생가죽</a>'},
        {level: '60', hunt: 'B', name: '스퀑크', location: '아발라시아 구름바다', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'B', name: '무용수 사누발리', location: '아발라시아 구름바다', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'A', name: '엔켈라도스', location: '아발라시아 구름바다', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'A', name: '시시우틀', location: '아발라시아 구름바다', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'S', name: '극락조', location: '아발라시아 구름바다', coordinate: '지도 참조', drop: '&nbsp'}
    ],
    Azys_Lla: [
        {level: '59', hunt: true, name: '메라시디아 드래고네트', location: '아지스 라', coordinate: '( 6.8, 35.4 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '메라시디아 드래곤', location: '아지스 라', coordinate: '( 8.3, 27.4 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '메라시디아 브로비냐크', location: '아지스 라', coordinate: '( 8.2, 32.7 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '메라시디아 암피프테레', location: '아지스 라', coordinate: '( 18.4, 31.3 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=12572\' id=\'drop\' target=\'_blank\'>암피프테레 생가죽</a>'},
        {level: '59', hunt: true, name: '메라시디아 뷔브르', location: '아지스 라', coordinate: '( 14.5, 35.2 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '메라시디아 팔라크', location: '아지스 라', coordinate: '( 15.7, 29.0 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '하급 하이드라', location: '아지스 라', coordinate: '( 13.0, 33.0 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '똑딱이 회전전차', location: '아지스 라', coordinate: '( 11.5, 13.8 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '부엉이곰', location: '아지스 라', coordinate: '( 13.7, 12.1 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '집행자 드로이드', location: '아지스 라', coordinate: '( 13.1, 17.2 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '알라그 태엽수확자', location: '아지스 라', coordinate: '( 13.4, 9.4 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '알라그 태엽정비병', location: '아지스 라', coordinate: '( 15.9, 12.1 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '알라그 태엽성기사', location: '아지스 라', coordinate: '( 13.0, 33.0 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '라미아 세포질잡종', location: '아지스 라', coordinate: '( 27.8, 11.3 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '라미아 단성생식종', location: '아지스 라', coordinate: '( 27.8, 11.3 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '알라그 키마이라', location: '아지스 라', coordinate: '( 31.2, 6.7 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=12599\' id=\'drop\' target=\'blank\'>키마이라 갈기</a>'},
        {level: '59', hunt: true, name: '엠푸사', location: '아지스 라', coordinate: '( 31.6, 11.4 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '외계 파충류', location: '아지스 라', coordinate: '( 33.9, 13.0 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '프로토 나가', location: '아지스 라', coordinate: '( 35.6, 8.0 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '시체꽃', location: '아지스 라', coordinate: '( 30.4, 12.3 )', drop: '&nbsp'},
        {level: '59', hunt: false, name: '마도 아다만손아귀', location: '아지스 라', coordinate: '( 27.7, 33.7 )', drop: '&nbsp'},
        {level: '59', hunt: false, name: '마도 콜로서스 III', location: '아지스 라', coordinate: '( 29.6, 28.9 )', drop: '&nbsp'},
        {level: '59', hunt: false, name: 'VI군단 뱅가드', location: '아지스 라', coordinate: '( 33.7, 37.8 )', drop: '&nbsp'},
        {level: '59', hunt: false, name: 'VI군단 도끼투사', location: '아지스 라', coordinate: '( 33.7, 37.8 )', drop: '&nbsp'},
        {level: '59', hunt: false, name: 'VI군단 격투사', location: '아지스 라', coordinate: '( 33.7, 37.8 )', drop: '&nbsp'},
        {level: '59', hunt: false, name: 'VI군단 비트', location: '아지스 라', coordinate: '( 33.7, 37.8 )', drop: '&nbsp'},
        {level: '59', hunt: false, name: 'VI군단 창투사', location: '아지스 라', coordinate: '( 33.7, 37.8 )', drop: '&nbsp'},
        {level: '59', hunt: false, name: 'VI군단 군단기수', location: '아지스 라', coordinate: '( 33.7, 37.8 )', drop: '&nbsp'},
        {level: '59', hunt: false, name: 'VI군단 검투사', location: '아지스 라', coordinate: '( 33.7, 37.8 )', drop: '&nbsp'},
        {level: '59', hunt: false, name: '알라그 태엽 비트', location: '아지스 라', coordinate: '( 38.8, 18.2 )', drop: '&nbsp'},
        {level: '60', hunt: false, name: '전쟁주먹', location: '아지스 라', coordinate: '( 23.9, 22.3 )', drop: '&nbsp'},
        {level: '60', hunt: false, name: '스핑크스', location: '아지스 라', coordinate: '( 23.9, 22.3 )', drop: '&nbsp'},
        {level: '60', hunt: 'B', name: '옴니', location: '아지스 라', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'B', name: '류키다스', location: '아지스 라', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'A', name: '악취화', location: '아지스 라', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'A', name: '캠파크티', location: '아지스 라', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'S', name: '레우크로타', location: '아지스 라', coordinate: '지도 참조', drop: '&nbsp'}
    ],
    The_Dravanian_Hinterlands: [
        {level: '58', hunt: true, name: '실잠자리', location: '저지 드라바니아', coordinate: '( 24.5, 21.1 )', drop: '&nbsp'},
        {level: '58', hunt: false, name: '태양곰', location: '저지 드라바니아', coordinate: '( 5.3, 27.1 )', drop: '&nbsp'},
        {level: '58', hunt: true, name: '혹등들소', location: '저지 드라바니아', coordinate: '( 34.1, 19.8 )', drop: '&nbsp'},
        {level: '58', hunt: true, name: '나르브루이', location: '저지 드라바니아', coordinate: '( 37.4, 24.1 )', drop: '&nbsp'},
        {level: '58', hunt: true, name: '큰독거미매', location: '저지 드라바니아', coordinate: '( 18.1, 12.9 )', drop: '&nbsp'},
        {level: '58', hunt: true, name: '거대 몰볼', location: '저지 드라바니아', coordinate: '( 11.2, 23.6 )', drop: '&nbsp'},
        {level: '58', hunt: true, name: '누에', location: '저지 드라바니아', coordinate: '( 12.3, 16.6 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=12600\' id=\'drop\' target=\'_blank\'>누에 고치</a>'},
        {level: '58', hunt: true, name: '온 콜리브리', location: '저지 드라바니아', coordinate: '( 15.7, 25.4 )', drop: '&nbsp'},
        {level: '58', hunt: true, name: '꿀먹이오소리', location: '저지 드라바니아', coordinate: '( 28.6, 27.0 )', drop: '&nbsp'},
        {level: '58', hunt: true, name: '고블린 칼부림꾼', location: '저지 드라바니아', coordinate: '( 31.2, 22.5 )', drop: '&nbsp'},
        {level: '58', hunt: true, name: '고블린 명사수', location: '저지 드라바니아', coordinate: '( 31.2, 22.5 )', drop: '&nbsp'},
        {level: '58', hunt: true, name: '고블린 땜장이', location: '저지 드라바니아', coordinate: '( 31.2, 22.5 )', drop: '&nbsp'},
        {level: '58', hunt: true, name: '고블린 조종사', location: '저지 드라바니아', coordinate: '( 31.2, 22.5 )', drop: '&nbsp'},
        {level: '58', hunt: true, name: 'III호 고블린탱크 E형', location: '저지 드라바니아', coordinate: '( 31.2, 22.5 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '오케아니스', location: '저지 드라바니아', coordinate: '( 14.0, 31.3 )', drop: '<a href=\'https://ff14.tar.to/item/list/?keyword=%EC%98%A4%EC%BC%80%EC%95%84%EB%8B%88%EC%8A%A4+%EA%B3%A0%EA%B8%B0\' id=\'drop\' target=\'_blank\'>오케아니스 고기</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EC%98%A4%EC%BC%80%EC%95%84%EB%8B%88%EC%8A%A4+%EC%95%8C\' id=\'drop\' target=\'_blank\'>오케아니스 알</a>'},
        {level: '59', hunt: true, name: '태양거머리', location: '저지 드라바니아', coordinate: '( 14.0, 31.3 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '오프켄', location: '저지 드라바니아', coordinate: '( 12.7, 33.9 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '포록고', location: '저지 드라바니아', coordinate: '( 12.4, 34.6 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '비페리케라스', location: '저지 드라바니아', coordinate: '( 22.6, 37.9 )', drop: '&nbsp'},
        {level: '59', hunt: true, name: '코카트리스', location: '저지 드라바니아', coordinate: '( 18.9, 35.0 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=12876\' id=\'drop\' target=\'_blank\'>코카트리스 고기</a>'},
        {level: '60', hunt: 'B', name: '프테리고투스', location: '저지 드라바니아', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'B', name: '기간토피테쿠스', location: '저지 드라바니아', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'A', name: '스톨라스', location: '저지 드라바니아', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'A', name: '기계병정 슬립킨크스', location: '저지 드라바니아', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'A', name: '창백의 기수', location: '저지 드라바니아', coordinate: '지도 참조', drop: '&nbsp'}
    ],
    Dravanian_Forelands: [
        {level: '52', hunt: true, name: '밴더스내치', location: '고지 드라바니아', coordinate: '( 32.8, 18.5 )', drop: '&nbsp'},
        {level: '52', hunt: true, name: '불곰', location: '고지 드라바니아', coordinate: '( 30.8, 11.8 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=12609\' id=\'drop\' target=\'_blank\'>곰 기름</a>'},
        {level: '52', hunt: true, name: '맑은강 낭카', location: '고지 드라바니아', coordinate: '( 28.5, 22.3 )', drop: '&nbsp'},
        {level: '52', hunt: true, name: '맑은강 닝키낭카', location: '고지 드라바니아', coordinate: '( 28.5, 22.3 )', drop: '&nbsp'},
        {level: '52', hunt: true, name: '잠자리용 감시자', location: '고지 드라바니아', coordinate: '( 28.3, 32.3 )', drop: '&nbsp'},
        {level: '52', hunt: true, name: '큰뿔산양', location: '고지 드라바니아', coordinate: '( 25.7, 29.7 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=12873\' id=\'drop\' target=\'_blank\'>큰뿔산양 고기</a>'},
        {level: '52', hunt: true, name: '야생 초코보', location: '고지 드라바니아', coordinate: '( 37.7, 23.8 )', drop: '&nbsp'},
        {level: '52', hunt: true, name: '깃털벼룩', location: '고지 드라바니아', coordinate: '( 36.2, 24.3 )', drop: '&nbsp'},
        {level: '52', hunt: true, name: '멜리아', location: '고지 드라바니아', coordinate: '( 28.5, 25.4 )', drop: '&nbsp'},
        {level: '52', hunt: true, name: '드라바니아 에이비스', location: '고지 드라바니아', coordinate: '( 27.1, 22.9 )', drop: '&nbsp'},
        {level: '52', hunt: false, name: '그나스 경작자', location: '고지 드라바니아', coordinate: '( 28.1, 34.9 )', drop: '&nbsp'},
        {level: '52', hunt: false, name: '그나스 강철요격자', location: '고지 드라바니아', coordinate: '( 28.1, 34.9 )', drop: '&nbsp'},
        {level: '52', hunt: false, name: '그나스 불꽃요격자', location: '고지 드라바니아', coordinate: '( 28.1, 34.9 )', drop: '&nbsp'},
        {level: '53', hunt: false, name: '그나스 우박요격자', location: '고지 드라바니아', coordinate: '( 30.4, 36.6 )', drop: '&nbsp'},
        {level: '53', hunt: false, name: '그나스 철갑요격자', location: '고지 드라바니아', coordinate: '( 30.4, 36.6 )', drop: '&nbsp'},
        {level: '53', hunt: false, name: '그나스 탐색자', location: '고지 드라바니아', coordinate: '( 30.4, 36.6 )', drop: '&nbsp'},
        {level: '53', hunt: true, name: '드라바니아 와이번', location: '고지 드라바니아', coordinate: '( 16.0, 33.4 )', drop: '<a href=\'https://ff14.tar.to/item/list/?keyword=%EC%99%80%EC%9D%B4%EB%B2%88+%EC%83%9D%EA%B0%80%EC%A3%BD\' id=\'drop\' target=\'_blank\'>와이번 생가죽</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EC%99%80%EC%9D%B4%EB%B2%88+%EB%82%A0%EA%B0%9C\' id=\'drop\' target=\'_blank\'>와이번 날개</a>'},
        {level: '53', hunt: true, name: '미아시드', location: '고지 드라바니아', coordinate: '( 19.6, 27.3 )', drop: '&nbsp'},
        {level: '53', hunt: true, name: '전방 히포세르프', location: '고지 드라바니아', coordinate: '( 17.1, 27.5 )', drop: '&nbsp'},
        {level: '53', hunt: true, name: '식초전갈용', location: '고지 드라바니아', coordinate: '( 13.5, 15.4 )', drop: '&nbsp'},
        {level: '53', hunt: true, name: '시리크타', location: '고지 드라바니아', coordinate: '( 13.5, 15.4 )', drop: '&nbsp'},
        {level: '53', hunt: true, name: '티라노사우르스', location: '고지 드라바니아', coordinate: '( 13.5, 15.4 )', drop: '&nbsp'},
        {level: '53', hunt: true, name: '갈리미무스', location: '고지 드라바니아', coordinate: '( 17.4, 16.9 )', drop: '&nbsp'},
        {level: '57', hunt: false, name: '잠자리용 추격자', location: '고지 드라바니아', coordinate: '( 29.9, 7.6 )', drop: '&nbsp'},
        {level: '57', hunt: true, name: '번개드래곤', location: '고지 드라바니아', coordinate: '( 29.9, 7.6 )', drop: 
        '<a href=\'https://ff14.tar.to/item/list/?keyword=%EB%93%9C%EB%9E%98%EA%B3%A4+%EC%83%9D%EA%B0%80%EC%A3%BD\' id=\'drop\' target=\'_blank\'>드래곤 생가죽</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EB%93%9C%EB%9E%98%EA%B3%A4+%EC%86%A1%EA%B3%B3%EB%8B%88\' id=\'drop\' target=\'_blank\'>드래곤 송곳니</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EC%9A%A9%EC%A1%B1%EC%9D%98+%ED%94%BC\' id=\'drop\' target=\'_blank\'>용족의 피</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EB%93%9C%EB%9E%98%EA%B3%A4%EC%9D%98+%EB%B9%84%EB%8A%98\' id=\'drop\' target=\'_blank\'>드래곤의 비늘</a>'},
        {level: '57', hunt: true, name: '로스 강철요격자', location: '고지 드라바니아', coordinate: '( 28.0, 36.3 )', drop: '&nbsp'},
        {level: '57', hunt: true, name: '로스 불꽃요격자', location: '고지 드라바니아', coordinate: '( 28.0, 36.3 )', drop: '&nbsp'},
        {level: '57', hunt: true, name: '로스 경작자', location: '고지 드라바니아', coordinate: '( 28.0, 36.3 )', drop: '&nbsp'},
        {level: '57', hunt: false, name: '금빛 밴더스내치', location: '고지 드라바니아', coordinate: '( 27.3, 7.9 )', drop: '&nbsp'},
        {level: '57', hunt: false, name: '해골 에이비스', location: '고지 드라바니아', coordinate: '( 12.3, 38.0 )', drop: '&nbsp'},
        {level: '60', hunt: 'B', name: '덱스타', location: '고지 드라바니아', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'B', name: '그나스 혜성요격자', location: '고지 드라바니아', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'A', name: '파일라스터', location: '고지 드라바니아', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'A', name: '와이번로드', location: '고지 드라바니아', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'S', name: '센무르', location: '고지 드라바니아', coordinate: '지도 참조', drop: '&nbsp'}
    ],
    The_Churning_Mists: [
        {level: '54', hunt: true, name: '로프켄', location: '드라바니아 구름바다', coordinate: '( 35.0, 33.1 )', drop: '&nbsp'},
        {level: '54', hunt: true, name: '상크친니', location: '드라바니아 구름바다', coordinate: '( 28.8, 32.5 )', drop: '&nbsp'},
        {level: '54', hunt: true, name: '암피프테레', location: '드라바니아 구름바다', coordinate: '( 16.0, 30.1 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=12572\' id=\'drop\' target=\'_blank\'>암피프테레 생가죽</a>'},
        {level: '54', hunt: true, name: '툴리핸드', location: '드라바니아 구름바다', coordinate: '( 33.3, 15.9 )', drop: '&nbsp'},
        {level: '54', hunt: true, name: '워제트', location: '드라바니아 구름바다', coordinate: '( 27.4, 20.1 )', drop: '&nbsp'},
        {level: '54', hunt: true, name: '이끼드래곤', location: '드라바니아 구름바다', coordinate: '( 23.2, 25.1 )', drop: 
        '<a href=\'https://ff14.tar.to/item/list/?keyword=%EB%93%9C%EB%9E%98%EA%B3%A4+%EC%83%9D%EA%B0%80%EC%A3%BD\' id=\'drop\' target=\'_blank\'>드래곤 생가죽</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EB%93%9C%EB%9E%98%EA%B3%A4+%EC%86%A1%EA%B3%B3%EB%8B%88\' id=\'drop\' target=\'_blank\'>드래곤 송곳니</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EC%9A%A9%EC%A1%B1%EC%9D%98+%ED%94%BC\' id=\'drop\' target=\'_blank\'>용족의 피</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EB%93%9C%EB%9E%98%EA%B3%A4%EC%9D%98+%EB%B9%84%EB%8A%98\' id=\'drop\' target=\'_blank\'>드래곤의 비늘</a>'},
        {level: '54', hunt: true, name: '작은 드래곤', location: '드라바니아 구름바다', coordinate: '( 20.4, 30.4 )', drop: '&nbsp'},
        {level: '54', hunt: false, name: '원시공룡', location: '드라바니아 구름바다', coordinate: '( 29.8, 23.9 )', drop: '&nbsp'},
        {level: '55', hunt: true, name: '장로 시리크타', location: '드라바니아 구름바다', coordinate: '( 34.3, 22.1 )', drop: '&nbsp'},
        {level: '55', hunt: true, name: '뷔브르', location: '드라바니아 구름바다', coordinate: '( 20.4, 17.2 )', drop: '&nbsp'},
        {level: '55', hunt: true, name: '장로 와이번', location: '드라바니아 구름바다', coordinate: '( 24.7, 28.1 )', drop: '<a href=\'https://ff14.tar.to/item/list/?keyword=%EC%99%80%EC%9D%B4%EB%B2%88+%EC%83%9D%EA%B0%80%EC%A3%BD\' id=\'drop\' target=\'_blank\'>와이번 생가죽</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EC%99%80%EC%9D%B4%EB%B2%88+%EB%82%A0%EA%B0%9C\' id=\'drop\' target=\'_blank\'>와이번 날개</a>'},
        {level: '55', hunt: true, name: '칼날 식초전갈용', location: '드라바니아 구름바다', coordinate: '( 18.3, 21.8 )', drop: '&nbsp'},
        {level: '55', hunt: true, name: '뒤틀린 멜리아', location: '드라바니아 구름바다', coordinate: '( 11.2, 20.3 )', drop: '&nbsp'},
        {level: '55', hunt: true, name: '안개도마뱀', location: '드라바니아 구름바다', coordinate: '( 11.5, 17.1 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=5449\' id=\'drop\' target=\'_blank\'>도마뱀 비늘</a>'},
        {level: '55', hunt: true, name: '안개 번개도마뱀', location: '드라바니아 구름바다', coordinate: '( 32.9, 32.5 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=5448\' id=\'drop\' target=\'_blank\'>번개도마뱀 비늘</a>'},
        {level: '55', hunt: true, name: '석회암 골렘', location: '드라바니아 구름바다', coordinate: '( 7.6, 13.7 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=5229\' id=\'drop\' target=\'_blank\'>이암</a>'},
        {level: '56', hunt: true, name: '드래고네트', location: '드라바니아 구름바다', coordinate: '( 19.0, 12.8 )', drop: '&nbsp'},
        {level: '56', hunt: true, name: '구름 에이비스', location: '드라바니아 구름바다', coordinate: '( 9.7, 36.8 )', drop: '&nbsp'},
        {level: '56', hunt: true, name: '핏빛 드래곤', location: '드라바니아 구름바다', coordinate: '( 26.0, 10.1 )', drop: 
        '<a href=\'https://ff14.tar.to/item/list/?keyword=%EB%93%9C%EB%9E%98%EA%B3%A4+%EC%83%9D%EA%B0%80%EC%A3%BD\' id=\'drop\' target=\'_blank\'>드래곤 생가죽</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EB%93%9C%EB%9E%98%EA%B3%A4+%EC%86%A1%EA%B3%B3%EB%8B%88\' id=\'drop\' target=\'_blank\'>드래곤 송곳니</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EC%9A%A9%EC%A1%B1%EC%9D%98+%ED%94%BC\' id=\'drop\' target=\'_blank\'>용족의 피</a><br><a href=\'https://ff14.tar.to/item/list/?keyword=%EB%93%9C%EB%9E%98%EA%B3%A4%EC%9D%98+%EB%B9%84%EB%8A%98\' id=\'drop\' target=\'_blank\'>드래곤의 비늘</a>'},
        {level: '56', hunt: true, name: '변종 드래곤', location: '드라바니아 구름바다', coordinate: '( 8.1, 19.2 )', drop: '&nbsp'},
        {level: '60', hunt: 'B', name: '허수아비전갈', location: '드라바니아 구름바다', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'B', name: '스키탈리스', location: '드라바니아 구름바다', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'A', name: '부네', location: '드라바니아 구름바다', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'A', name: '아가토스', location: '드라바니아 구름바다', coordinate: '지도 참조', drop: '&nbsp'},
        {level: '60', hunt: 'S', name: '간다르바', location: '드라바니아 구름바다', coordinate: '지도 참조', drop: '&nbsp'}
    ]
};