let DATA = {
    The_Fringes: [
        {level: '60', name: '례쉬', location: '기라바니아 변방지대', coordinate: '( 11.0, 13.6 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19930\' id=\'drop\' target=\'_blank\'>너도밤나무 원목</a>'},
        {level: '60', name: '가젤매', location: '기라바니아 변방지대', coordinate: '( 11.8, 13.3 )', drop: '&nbsp'},
        {level: '60', name: '사프리아', location: '기라바니아 변방지대', coordinate: '( 10.0, 14.6 )', drop: '&nbsp'},
        {level: '60', name: '벨로디나 사르코수쿠스', location: '기라바니아 변방지대', coordinate: '( 18.0, 11.8 )', drop: '&nbsp'},
        {level: '60', name: '작은 가가나', location: '기라바니아 변방지대', coordinate: '( 21.9, 10.6 )', drop: '&nbsp'},
        {level: '60', name: '물레거미', location: '기라바니아 변방지대', coordinate: '( 21.9, 10.6 )', drop: '&nbsp'},
        {level: '60', name: '포퍼', location: '기라바니아 변방지대', coordinate: '( 21.8, 13.2 )', drop: '&nbsp'},
        {level: '60', name: '먼지 다라', location: '기라바니아 변방지대', coordinate: '( 26.4, 13.8 )', drop: '&nbsp'},
        {level: '60', name: '차디찬 브후트', location: '기라바니아 변방지대', coordinate: '( 25.2, 16.0 )', drop: '&nbsp'},
        {level: '60', name: '벨로디나 푸길', location: '기라바니아 변방지대', coordinate: '( 27.9, 15.8 )', drop: '&nbsp'},
        {level: '61', name: '산악 회색곰', location: '기라바니아 변방지대', coordinate: '( 10.7, 17.5 )', drop: '&nbsp'},
        {level: '61', name: '이끼이끼', location: '기라바니아 변방지대', coordinate: '( 11.6, 18.0 )', drop: '&nbsp'},
        {level: '61', name: '물잠자리', location: '기라바니아 변방지대', coordinate: '( 11.6, 22.8 )', drop: '&nbsp'},
        {level: '61', name: '디아카', location: '기라바니아 변방지대', coordinate: '( 10.9, 27.6 )', drop: '&nbsp'},
        {level: '61', name: '기러기아귀', location: '기라바니아 변방지대', coordinate: '( 10.3, 28.5 )', drop: '&nbsp'},
        {level: '61', name: '개미귀신 추격자', location: '기라바니아 변방지대', coordinate: '( 15.4, 23.5 )', drop: '&nbsp'},
        {level: '67', name: '텔레오케라스', location: '기라바니아 변방지대', coordinate: '( 28.7, 23.5 )', drop: '&nbsp'},
        {level: '67', name: '개미귀신 추적자', location: '기라바니아 변방지대', coordinate: '( 30.4, 27.8 )', drop: '&nbsp'},
        {level: '67', name: '개미귀신 잠복자', location: '기라바니아 변방지대', coordinate: '( 31.5, 28.2 )', drop: '&nbsp'},
        {level: '67', name: '가젤', location: '기라바니아 변방지대', coordinate: '( 25.7, 29.2 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19920\' id=\'drop\' target=\'_blank\'>가젤 뿔</a><br><a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=20003\' id=\'drop\' target=\'_blank\'>가젤 생가죽</a>'},
        {level: '67', name: '칼리아나 크샤트리아', location: '기라바니아 변방지대', coordinate: '( 34.3, 25.3 )', drop: '&nbsp'},
        {level: '67', name: '칼리아나 수드라', location: '기라바니아 변방지대', coordinate: '( 34.3, 25.3 )', drop: '&nbsp'},
        {level: '67', name: '칼리아나 브라만', location: '기라바니아 변방지대', coordinate: '( 34.3, 25.3 )', drop: '&nbsp'},
        {level: '67', name: '성스러운 마리드', location: '기라바니아 변방지대', coordinate: '( 34.3, 25.3 )', drop: '&nbsp'}
    ],
    The_Peaks: [
        {level: '60', name: '먼지 아닐라', location: '기라바니아 산악지대', coordinate: '( 21.6, 13.6 )', drop: '&nbsp'},
        {level: '60', name: '키키룬 고기냠냠이', location: '기라바니아 산악지대', coordinate: '( 17.3, 15.9 )', drop: '&nbsp'},
        {level: '60', name: '반짝나비', location: '기라바니아 산악지대', coordinate: '( 13.2, 10.3 )', drop: '&nbsp'},
        {level: '60', name: '기라바니아 뿔부리', location: '기라바니아 산악지대', coordinate: '( 10.1, 7.5 )', drop: '&nbsp'},
        {level: '60', name: '큰메뚜기', location: '기라바니아 산악지대', coordinate: '( 20.2, 7.4 )', drop: '&nbsp'},
        {level: '60', name: '핏빛날개나방', location: '기라바니아 산악지대', coordinate: '( 17.2, 11.0 )', drop: '&nbsp'},
        {level: '61', name: '바위발톱', location: '기라바니아 산악지대', coordinate: '( 26.5, 8.2 )', drop: '&nbsp'},
        {level: '61', name: '기라바니아 쇠똥구리', location: '기라바니아 산악지대', coordinate: '( 25.0, 13.8 )', drop: '&nbsp'},
        {level: '61', name: '키키룬 고기싹둑이', location: '기라바니아 산악지대', coordinate: '( 26.7, 20.6 )', drop: '&nbsp'},
        {level: '61', name: '루드수드', location: '기라바니아 산악지대', coordinate: '( 31.8, 9.0 )', drop: '&nbsp'},
        {level: '61', name: '대리석 요결석', location: '기라바니아 산악지대', coordinate: '( 35.5, 8.9 )', drop: '&nbsp'},
        {level: '68', name: '높은날개 큰메뚜기', location: '기라바니아 산악지대', coordinate: '( 14.0, 35.8 )', drop: '&nbsp'},
        {level: '68', name: '판테라', location: '기라바니아 산악지대', coordinate: '( 12.4, 31.1 )', drop: '&nbsp'},
        {level: '68', name: '콩가마토', location: '기라바니아 산악지대', coordinate: '( 14.6, 25.2 )', drop: '&nbsp'},
        {level: '68', name: '순종 그리핀', location: '기라바니아 산악지대', coordinate: '( 25.2, 24.7 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=20004\' id=\'drop\' target=\'_blank\'>순종 그리핀 생가죽</a>'},
        {level: '68', name: '잠멜', location: '기라바니아 산악지대', coordinate: '( 25.7, 29.7 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19875\' id=\'drop\' target=\'_blank\'>잠멜 고기</a>'},
        {level: '68', name: '고원 에루카', location: '기라바니아 산악지대', coordinate: '( 24.3, 33.6 )', drop: '&nbsp'}
    ],
    The_Lochs: [
        {level: '69', name: '칼루크', location: '기라바니아 호반지대', coordinate: '( 10.8, 17.5 )', drop: '&nbsp'},
        {level: '69', name: '로흐 거머리', location: '기라바니아 호반지대', coordinate: '( 17.2, 14.6 )', drop: '&nbsp'},
        {level: '69', name: '로흐 낭카', location: '기라바니아 호반지대', coordinate: '( 17.4, 16.1 )', drop: '&nbsp'},
        {level: '69', name: '켈로네', location: '기라바니아 호반지대', coordinate: '( 26.2, 14.4 )', drop: '&nbsp'},
        {level: '69', name: '아발라시아 미노타우로스', location: '기라바니아 호반지대', coordinate: '( 29.0, 9.1 )', drop: '&nbsp'},
        {level: '69', name: '근위 브후트', location: '기라바니아 호반지대', coordinate: '( 24.4, 9.2 )', drop: '&nbsp'},
        {level: '69', name: '그림자요괴', location: '기라바니아 호반지대', coordinate: '( 18.5, 7.3 )', drop: '&nbsp'},
        {level: '69', name: '땅을 기는 에딜라', location: '기라바니아 호반지대', coordinate: '( 7.6, 8.0 )', drop: '&nbsp'},
        {level: '69', name: '염호 아닐라', location: '기라바니아 호반지대', coordinate: '( 5.0, 15.6 )', drop: '&nbsp'},
        {level: '69', name: '소브란', location: '기라바니아 호반지대', coordinate: '( 15.1, 22.7 )', drop: '&nbsp'},
        {level: '69', name: '염호 다라', location: '기라바니아 호반지대', coordinate: '( 13.2, 29.7 )', drop: '&nbsp'},
        {level: '69', name: '아바돈', location: '기라바니아 호반지대', coordinate: '( 19.1, 31.9 )', drop: '&nbsp'},
        {level: '69', name: '베파르', location: '기라바니아 호반지대', coordinate: '( 24.2, 30.3 )', drop: '&nbsp'},
        {level: '69', name: '포배드', location: '기라바니아 호반지대', coordinate: '( 23.3, 25.9 )', drop: '&nbsp'},
        {level: '69', name: '드루바', location: '기라바니아 호반지대', coordinate: '( 22.8, 22.9 )', drop: '&nbsp'},
        {level: '69', name: '탈라시나', location: '기라바니아 호반지대', coordinate: '( 19.6, 26.1 )', drop: '&nbsp'},
        {level: '69', name: '산악 찰흙야수', location: '기라바니아 호반지대', coordinate: '( 5.6, 26.3 )', drop: '&nbsp'}
    ],
    Ruby_Sea: [
        {level: '62', name: '해마', location: '홍옥해', coordinate: '( 30.0, 38.3 )', drop: '&nbsp'},
        {level: '62', name: '가시봄', location: '홍옥해', coordinate: '( 30.0, 38.3 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19923\' id=\'drop\' target=\'_blank\'>가시봄 가시</a>'},
        {level: '62', name: '가사메', location: '홍옥해', coordinate: '( 25.9, 36.6 )', drop: '&nbsp'},
        {level: '62', name: '지옥 아날라', location: '홍옥해', coordinate: '( 25.9, 36.6 )', drop: '&nbsp'},
        {level: '62', name: '날상어', location: '홍옥해', coordinate: '( 29.0, 31.5 )', drop: '&nbsp'},
        {level: '62', name: '귀신물범', location: '홍옥해', coordinate: '( 18.5, 10.3 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=20000\' id=\'drop\' target=\'_blank\'>귀신물범 생가죽</a>'},
        {level: '62', name: '시라누이', location: '홍옥해', coordinate: '( 18.6, 7.2 )', drop: '&nbsp'},
        {level: '62', name: '큰바다뱀', location: '홍옥해', coordinate: '( 30.2, 7.7 )', drop: '&nbsp'},
        {level: '62', name: '산호게', location: '홍옥해', coordinate: '( 32.3, 3.7 )', drop: '&nbsp'},
        {level: '62', name: '꿈고둥', location: '홍옥해', coordinate: '( 32.3, 3.7 )', drop: '&nbsp'},
        {level: '62', name: '철갑게', location: '홍옥해', coordinate: '( 35.6, 21.6 )', drop: '&nbsp'},
        {level: '63', name: '아파', location: '홍옥해', coordinate: '( 17.7, 35.3 )', drop: '&nbsp'},
        {level: '63', name: '줄가오리', location: '홍옥해', coordinate: '( 8.2, 26.6 )', drop: '&nbsp'},
        {level: '63', name: '붉은등 부칸', location: '홍옥해', coordinate: '( 8.2, 26.6 )', drop: '&nbsp'},
        {level: '63', name: '붉은등 효우에', location: '홍옥해', coordinate: '( 8.2, 26.6 )', drop: '&nbsp'},
        {level: '63', name: '붉은등 혼칸', location: '홍옥해', coordinate: '( 8.2, 26.6 )', drop: '&nbsp'},
        {level: '63', name: '거단', location: '홍옥해', coordinate: '( 8.5, 6.2 )', drop: '&nbsp'},
        {level: '63', name: '꿈고둥 알맹이', location: '홍옥해', coordinate: '( 25.3, 26.9 )', drop: '&nbsp'},
        {level: '63', name: '붉은뿔부리', location: '홍옥해', coordinate: '( 34.3, 23.0 )', drop: '&nbsp'}
    ],
    YANXIA: [
        {level: '64', name: '미노비', location: '얀샤', coordinate: '( 33.1, 17.2 )', drop: '&nbsp'},
        {level: '64', name: '얀샤 호랑이', location: '얀샤', coordinate: '( 37.5, 15.9 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=20001\' id=\'drop\' target=\'_blank\'>호랑이 생가죽</a>'},
        {level: '64', name: '장수풍뎅이', location: '얀샤', coordinate: '( 31.0, 22.6 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19924\' id=\'drop\' target=\'_blank\'>장수풍뎅이 갑각</a>'},
        {level: '64', name: '무이강 붉은뿔부리', location: '얀샤', coordinate: '( 31.7, 26.1 )', drop: '&nbsp'},
        {level: '64', name: '도마 족제비', location: '얀샤', coordinate: '( 33.3, 29.8 )', drop: '&nbsp'},
        {level: '64', name: '물뱀', location: '얀샤', coordinate: '( 24.4, 26.3 )', drop: '&nbsp'},
        {level: '64', name: '인랑족 칼잡이', location: '얀샤', coordinate: '( 23.9, 28.9 )', drop: '&nbsp'},
        {level: '64', name: '인랑족 활잡이', location: '얀샤', coordinate: '( 23.9, 28.9 )', drop: '&nbsp'},
        {level: '64', name: '인랑족 창잡이', location: '얀샤', coordinate: '( 23.9, 28.9 )', drop: '&nbsp'},
        {level: '64', name: '바나라', location: '얀샤', coordinate: '( 23.4, 30.8 )', drop: '&nbsp'},
        {level: '64', name: '긴팔이', location: '얀샤', coordinate: '( 24.9, 33.4 )', drop: '&nbsp'},
        {level: '64', name: '타오취엔', location: '얀샤', coordinate: '( 30.5, 35.1 )', drop: '&nbsp'},
        {level: '64', name: '겐스이 아파', location: '얀샤', coordinate: '( 20.9, 33.8 )', drop: '&nbsp'},
        {level: '64', name: '팔방조', location: '얀샤', coordinate: '( 18.1, 31.3 )', drop: '&nbsp'},
        {level: '64', name: '코자', location: '얀샤', coordinate: '( 14.8, 29.6 )', drop: '&nbsp'},
        {level: '67', name: '무지개 호랑이', location: '얀샤', coordinate: '( 27.4, 12.1 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=20001\' id=\'drop\' target=\'_blank\'>호랑이 생가죽</a>'},
        {level: '67', name: '에비스 나마즈오', location: '얀샤', coordinate: '( 29.0, 7.9 )', drop: '&nbsp'},
        {level: '67', name: '흰날개 붉은뿔부리', location: '얀샤', coordinate: '( 20.2, 13.6 )', drop: '&nbsp'},
        {level: '67', name: '마가츠 코자', location: '얀샤', coordinate: '( 18.7, 10.5 )', drop: '&nbsp'},
        {level: '67', name: '마가츠 키요후사', location: '얀샤', coordinate: '( 18.7, 10.5 )', drop: '&nbsp'}
    ],
    AZIM_STEPPE: [
        {level: '65', name: '긴털들소', location: '아짐 대초원', coordinate: '( 30.2, 30.1 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19873\' id=\'drop\' target=\'_blank\'>긴털들소 앞다릿살</a><br><a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19921\' id=\'drop\' target=\'_blank\'>긴털들소 뿔</a>'},
        {level: '65', name: '마타마타', location: '아짐 대초원', coordinate: '( 23.6, 13.6 )', drop: '&nbsp'},
        {level: '65', name: '훈 촐로오', location: '아짐 대초원', coordinate: '( 13.0, 14.0 )', drop: '&nbsp'},
        {level: '65', name: '모오 쇼보오', location: '아짐 대초원', coordinate: '( 23.7, 10.5 )', drop: '&nbsp'},
        {level: '65', name: '매머드', location: '아짐 대초원', coordinate: '( 28.9, 17.5 )', drop: '&nbsp'},
        {level: '65', name: '풀볼', location: '아짐 대초원', coordinate: '( 32.8, 21.0 )', drop: '&nbsp'},
        {level: '65', name: '초원 거단', location: '아짐 대초원', coordinate: '( 34.4, 23.8 )', drop: '&nbsp'},
        {level: '65', name: '초원 긴팔이', location: '아짐 대초원', coordinate: '( 28.8, 28.1 )', drop: '&nbsp'},
        {level: '65', name: '할가이', location: '아짐 대초원', coordinate: '( 21.4, 18.6 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19985\' id=\'drop\' target=\'_blank\'>할가이 갈기</a>'},
        {level: '66', name: '윙윙잠자리', location: '아짐 대초원', coordinate: '( 23.3, 31.7 )', drop: '&nbsp'},
        {level: '66', name: '카오츄', location: '아짐 대초원', coordinate: '( 19.9, 29.8 )', drop: '&nbsp'},
        {level: '66', name: '만자시리', location: '아짐 대초원', coordinate: '( 16.9, 34.2 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=19986\' id=\'drop\' target=\'_blank\'>만자시리 털</a>'},
        {level: '66', name: '초원 아날라', location: '아짐 대초원', coordinate: '( 14.6, 30.8 )', drop: '&nbsp'},
        {level: '66', name: '굴로굴로', location: '아짐 대초원', coordinate: '( 13.6, 27.3 )', drop: '&nbsp'},
        {level: '66', name: '바르스', location: '아짐 대초원', coordinate: '( 12.0, 22.8 )', drop: '<a href=\'http://ff14.inven.co.kr/dataninfo/item/detail.php?code=20001\' id=\'drop\' target=\'_blank\'>호랑이 생가죽</a>'},
        {level: '66', name: '마탕가', location: '아짐 대초원', coordinate: '( 10.0, 20.1 )', drop: '&nbsp'}
    ]
};